import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir,stat} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import worker from '../worker.mjs';
const origin='https://www.nathonline.com.np';
const payload={name:'Synthetic Test',phone:'9800000000',service:'education',message:'Synthetic test enquiry',consent:true,website:''};
async function setup(){
 const sqlite=new DatabaseSync(':memory:');
 sqlite.exec(await readFile('migrations/0001_enquiries.sql','utf8'));
 const DB={prepare(sql){return {bind(...args){return {first:async()=>sqlite.prepare(sql).get(...args),run:async()=>sqlite.prepare(sql).run(...args)};},run:async()=>sqlite.prepare(sql).run()};}};
 return {sqlite,env:{APP_ENV:'production',SUBMISSIONS_ENABLED:'true',REQUEST_LIMITER:{limit:async()=>({success:true})},DB}};
}
const post=(path,data=payload,key=crypto.randomUUID(),extra={})=>new Request(origin+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,...extra},body:JSON.stringify(data)});
test('repeated requests save exactly once; changed retry is rejected',async()=>{const {sqlite,env}=await setup();const key=crypto.randomUUID();const responses=await Promise.all(Array.from({length:5},()=>worker.fetch(post('/api/requests',payload,key),env)));const bodies=await Promise.all(responses.map(r=>r.json()));assert.equal(new Set(bodies.map(b=>b.reference)).size,1);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM enquiries').get().n,1);assert.equal((await worker.fetch(post('/api/requests',{...payload,message:'Changed details'},key),env)).status,409);sqlite.close();});
test('tracking reveals only generic status and requires matching phone',async()=>{const {sqlite,env}=await setup();const saved=await (await worker.fetch(post('/api/requests'),env)).json();assert.deepEqual(await (await worker.fetch(post('/api/track',{reference:saved.reference,phone:'+977 9800000000'}),env)).json(),{status:'new'});assert.deepEqual(await (await worker.fetch(post('/api/track',{reference:saved.reference,phone:'9811111111'}),env)).json(),{status:null});sqlite.close();});
test('validation, hostile origins, large bodies and throttling do not save',async()=>{const {sqlite,env}=await setup();assert.equal((await worker.fetch(post('/api/requests',{...payload,phone:'123'}),env)).status,422);assert.equal((await worker.fetch(post('/api/requests',payload,crypto.randomUUID(),{Origin:'https://evil.example'}),env)).status,403);assert.equal((await worker.fetch(post('/api/requests',{...payload,message:'x'.repeat(9000)}),env)).status,413);assert.equal((await worker.fetch(post('/api/requests'),{...env,REQUEST_LIMITER:{limit:async()=>({success:false})}})).status,429);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM enquiries').get().n,0);sqlite.close();});
test('storage failures never produce a success receipt',async()=>{const {env,sqlite}=await setup();const r=await worker.fetch(post('/api/requests'),{...env,DB:undefined});assert.equal(r.status,503);assert.ok(!(await r.json()).reference);sqlite.close();});
test('HTTPS redirects preserve path, API GET is 405, security headers cover errors',async()=>{const {env,sqlite}=await setup();const r=await worker.fetch(new Request('http://nathonline.com.np/services?x=1'),env);assert.equal(r.status,308);assert.equal(r.headers.get('Location'),origin+'/services?x=1');const get=await worker.fetch(new Request(origin+'/api/requests'),env);assert.equal(get.status,405);assert.equal(get.headers.get('Allow'),'POST');assert.match(get.headers.get('Content-Security-Policy'),/frame-ancestors 'none'/);sqlite.close();});
test('retention removes only closed records past ninety days',async()=>{const {sqlite,env}=await setup();const saved=await(await worker.fetch(post('/api/requests'),env)).json();sqlite.prepare("UPDATE enquiries SET status='closed',closed_at=datetime('now') WHERE reference=?").run(saved.reference);assert.ok(sqlite.prepare('SELECT closed_at FROM enquiries').get().closed_at);await worker.scheduled({},env);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM enquiries').get().n,1);sqlite.prepare("UPDATE enquiries SET closed_at=datetime('now','-91 days')").run();await worker.scheduled({},env);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM enquiries').get().n,0);sqlite.close();});
test('all 38 pages have language, headings, canonical metadata and valid internal files',async()=>{let count=0;async function scan(dir){for(const e of await readdir(dir,{withFileTypes:true})){const file=`${dir}/${e.name}`;if(e.isDirectory()){await scan(file);continue;}if(!file.endsWith('.html'))continue;count++;const html=await readFile(file,'utf8');assert.match(html,/<html lang="(en|ne)">/);assert.equal((html.match(/<h1>/g)||[]).length,1,file);assert.match(html,/rel="canonical"/);assert.ok(!html.includes('style="'));for(const m of html.matchAll(/(?:href|src)="(\/[^"#]*)"/g)){const path=m[1].split('?')[0];if(path==='/cdn-cgi/access/logout')continue;const options=[`dist${path}`,`dist${path}.html`,`dist${path.replace(/\/$/,'')}/index.html`];let found=false;for(const option of options){try{if((await stat(option)).isFile())found=true;}catch{}}assert.ok(found,`${file}: ${path}`);}}}await scan('dist');assert.equal(count,38);});
