const $=s=>document.querySelector(s),notice=$('#admin-notice');
let page=0,current=null,services=[],exportQuery={q:"",status:"",page:0};
const nepalTime=value=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kathmandu',dateStyle:'medium',timeStyle:'short'}).format(new Date(value.includes('T')?value:value.replace(' ','T')+'Z'))+' NPT';
const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;};
async function api(path,method='GET',body){const response=await fetch('/admin/api'+path,{method,headers:{'Content-Type':'application/json','X-Nath-Admin':'1'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});let data;try{data=await response.json();}catch{throw Error('Please sign in again or ask the owner to finish admin setup.');}if(!response.ok)throw Error(data.error||'Unable to complete this action');return data;}
async function action(fn){notice.textContent='Working…';try{await fn();notice.textContent='Ready';}catch(e){notice.textContent=e.message;notice.focus();}}
async function overview(){const {counts}=await api('/overview');const box=$('#overview');box.replaceChildren();for(const [key,label] of [['new','New'],['contacted','Contacted'],['in_progress','In progress'],['closed','Closed']]){const card=text('article','','overview-card');card.append(text('strong',String(counts[key]||0)),text('span',label));box.append(card);}}
async function requests(){await overview();await retention();const q=$('#request-query').value.trim(),status=$('#request-status').value;const data=await api(`/requests?q=${encodeURIComponent(q)}&status=${status}&page=${page}`);exportQuery={q,status,page};const list=$('#request-list');list.replaceChildren();if(!data.requests.length)list.append(text('p','No matching requests.'));
 for(const r of data.requests){const card=text('article','','request-row');const button=text('button',r.reference,'text-link');button.type='button';button.addEventListener('click',()=>action(()=>detail(r.reference)));card.append(button,text('strong',r.name),text('span',r.phone),text('span',`${r.status.replaceAll('_',' ')}${r.outcome?' · '+r.outcome:''}`),text('small',nepalTime(r.created_at)));list.append(card);}
 $('#previous-page').disabled=page===0;$('#next-page').disabled=!data.hasMore;$('#page-number').textContent=`Page ${page+1}`;
}
async function detail(reference){const d=await api('/requests/'+reference);current=d.record;const box=$('#request-detail');box.hidden=false;$('#detail-reference').textContent=reference;$('#detail-name').textContent=current.name+' · '+current.phone;$('#detail-service').textContent=current.service_title||current.service_id||current.service;$('#detail-message').textContent=current.message;$('#detail-created').textContent='Submitted '+nepalTime(current.created_at);$('#edit-status').value=current.status;$('#edit-outcome').value=current.outcome;$('#internal-note').value=current.internal_note;const history=$('#request-history');history.replaceChildren();for(const event of d.events)history.append(text('li',`${nepalTime(event.created_at)} · ${event.from_status} → ${event.to_status}${event.outcome?' / '+event.outcome:''} · ${event.actor}`));await loadFinance(reference);box.scrollIntoView({behavior:'smooth',block:'start'});$('#detail-reference').focus();}
$('#request-search').addEventListener('submit',e=>{e.preventDefault();page=0;action(requests);});
$('#previous-page').addEventListener('click',()=>{page--;action(requests);});$('#next-page').addEventListener('click',()=>{page++;action(requests);});
$('#request-edit').addEventListener('submit',e=>{e.preventDefault();if(!current)return;const button=e.submitter;button.disabled=true;action(async()=>{await api('/requests/'+current.reference,'PATCH',{version:current.version,status:$('#edit-status').value,outcome:$('#edit-status').value==='closed'?$('#edit-outcome').value:'',internal_note:$('#internal-note').value});await detail(current.reference);await requests();}).finally(()=>button.disabled=false);});
$('#edit-status').addEventListener('change',()=>{$('#edit-outcome').required=$('#edit-status').value==='closed';});
async function loadServices(){const data=await api('/services');services=data.services;renderServices();}
function renderServices(){const query=$('#service-search').value.trim().toLowerCase(),visibility=$('#service-visibility').value;const filtered=services.filter(s=>(s.title_en+' '+s.title_ne).toLowerCase().includes(query)&&(visibility==='all'||(visibility==='visible'?s.active:!s.active)));$('#service-count').textContent=filtered.length+' services shown';const list=$('#admin-services');list.replaceChildren();for(const s of filtered){const card=text('article','','request-row');card.append(text('strong',s.title_en),text('span',s.active?'Visible':'Removed / hidden'),text('span',`From Rs. ${s.starting_price}`));const edit=text('button','Edit','button secondary');edit.type='button';edit.addEventListener('click',()=>editService(s));card.append(edit);if(s.active){const remove=text('button','Remove from website','button secondary');remove.type='button';remove.addEventListener('click',()=>{if(confirm('Remove this service from the public catalogue? Existing requests will remain available.'))action(async()=>{await api('/services/'+s.id,'DELETE',{version:s.version});await loadServices();});});card.append(remove);}else{const restore=text('button','Restore service','button secondary');restore.type='button';restore.addEventListener('click',()=>action(async()=>{await api('/services','POST',{...s,items:JSON.parse(s.items_json),active:true});await loadServices();}));card.append(restore);}list.append(card);}}
function editService(s){const form=$('#service-edit');form.reset();form.hidden=false;for(const k of ['id','category','icon','title_en','title_ne','description_en','description_ne','note_en','note_ne','starting_price'])form.elements[k].value=s?.[k]??(k==='starting_price'?100:'');form.elements.version.value=s?.version||0;form.elements.id.readOnly=!!s;form.elements.active.checked=s?!!s.active:true;const items=s?JSON.parse(s.items_json):[];form.elements.items_en.value=items.map(x=>x[0]).join('\n');form.elements.items_ne.value=items.map(x=>x[1]).join('\n');form.scrollIntoView({behavior:'smooth',block:'start'});form.elements.title_en.focus();}
$('#add-service').addEventListener('click',()=>editService(null));
$('#service-edit').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const d=Object.fromEntries(new FormData(form));const en=d.items_en.split('\n').map(x=>x.trim()).filter(Boolean),ne=d.items_ne.split('\n').map(x=>x.trim()).filter(Boolean);if(en.length!==ne.length){notice.textContent='Enter the same number of English and Nepali service items.';return;}d.items=en.map((x,i)=>[x,ne[i]]);d.version=Number(d.version);d.starting_price=Number(d.starting_price);d.active=form.elements.active.checked;const button=e.submitter;button.disabled=true;action(async()=>{await api('/services','POST',d);form.hidden=true;await loadServices();}).finally(()=>button.disabled=false);});
action(async()=>{const me=await api('/me');$('#admin-email').textContent=me.email;await requests();await loadServices();});

document.querySelector('#sign-out').addEventListener('click',()=>action(async()=>{const r=await fetch('/admin/auth/logout',{method:'POST',headers:{'Content-Type':'application/json','X-Nath-Admin':'1'},body:'{}'});if(!r.ok)throw Error('Unable to sign out. Try again.');location.replace('/admin/login');}));

$('#service-search').addEventListener('input',renderServices);
$('#service-visibility').addEventListener('change',renderServices);
$('#cancel-service').addEventListener('click',()=>{$('#service-edit').hidden=true;$('#add-service').focus();});

let financeRecord=null;
const money=p=>new Intl.NumberFormat('en-NP',{style:'currency',currency:'NPR'}).format(p/100);
function quoteRow(item={description:'',kind:'service',paisa:0}){
 const row=text('div','','quote-row');
 const description=document.createElement('input');description.value=item.description;description.placeholder='Charge description';description.setAttribute('aria-label','Charge description');description.maxLength=160;description.required=true;
 const kind=document.createElement('select');kind.setAttribute('aria-label','Charge type');for(const [value,label] of [['service','Nath service charge'],['provider','Official / provider fee']]){const option=text('option',label);option.value=value;kind.append(option);}kind.value=item.kind;
 const amount=document.createElement('input');amount.type='number';amount.min='0';amount.max='1000000';amount.step='0.01';amount.required=true;amount.value=(item.paisa/100).toFixed(2);amount.setAttribute('aria-label','Amount in NPR');
 const remove=text('button','Remove','button secondary');remove.type='button';remove.addEventListener('click',()=>{row.remove();quoteTotal();});row.append(description,kind,amount,remove);amount.addEventListener('input',quoteTotal);$('#quote-items').append(row);
}
function quoteItems(){return [...$('#quote-items').children].map(row=>({description:row.children[0].value,kind:row.children[1].value,paisa:Math.round(Number(row.children[2].value)*100)}));}
function quoteTotal(){const total=quoteItems().reduce((n,x)=>n+x.paisa,0),paid=Math.round(Number($('#paid-total').value)*100);$('#quote-total').textContent=`Quote: ${money(total)} · Received: ${money(paid)} · Balance: ${money(total-paid)} · ${paid===0?'Unpaid':paid<total?'Partially paid':paid===total?'Paid':'Check overpayment'}`;}
async function loadFinance(reference){financeRecord=await api('/requests/'+reference+'/finance');$('#quote-items').replaceChildren();for(const item of financeRecord.items)quoteRow(item);if(!financeRecord.items.length)quoteRow();$('#paid-total').value=(financeRecord.paid_paisa/100).toFixed(2);$('#payment-note').value='';quoteTotal();$('#print-quote').disabled=!financeRecord.items.length;const history=$('#finance-history');history.replaceChildren();for(const e of financeRecord.history)history.append(text('li',`${nepalTime(e.created_at)} · Quote ${money(JSON.parse(e.quote_json).reduce((n,x)=>n+x.paisa,0))} · Received ${money(e.paid_paisa)} · ${e.payment_note}`));}
$('#quote-add').addEventListener('click',()=>{if($('#quote-items').children.length>=20){notice.textContent='Maximum 20 charges per quote.';return;}quoteRow();});
$('#paid-total').addEventListener('input',quoteTotal);
$('#finance-form').addEventListener('submit',event=>{event.preventDefault();if(!current||!financeRecord)return;const button=event.submitter;button.disabled=true;action(async()=>{await api('/requests/'+current.reference+'/finance','PATCH',{version:financeRecord.version,items:quoteItems(),paid_paisa:Math.round(Number($('#paid-total').value)*100),payment_note:$('#payment-note').value});await loadFinance(current.reference);}).finally(()=>button.disabled=false);});
$('#print-quote').addEventListener('click',()=>{if(!financeRecord?.items.length)return;let sheet=$('#print-sheet');if(!sheet){sheet=text('section','','print-sheet');sheet.id='print-sheet';document.body.append(sheet);}sheet.replaceChildren(text('h1','Nath Online Services — Quote'),text('p','Butwal, Nepal · +977 9867302353'),text('p',current.reference),text('p',current.name));for(const item of financeRecord.items)sheet.append(text('p',`${item.description} (${item.kind==='service'?'Service charge':'Official / provider fee'}) — ${money(item.paisa)}`));const total=financeRecord.items.reduce((n,x)=>n+x.paisa,0);sheet.append(text('strong',`Total: ${money(total)}`),text('p',`Recorded received: ${money(financeRecord.paid_paisa)} · Balance: ${money(total-financeRecord.paid_paisa)}`),text('p','Subject to customer approval. This quote is not a tax invoice or proof of payment.'));window.print();});

async function retention(){const data=await api('/retention');$('#retention-summary').textContent=`Closed requests and their linked quote/payment history are deleted after ${data.days} days. ${data.due_soon} reach that age within seven days; ${data.eligible} are eligible for the next cleanup. Open requests are kept.`;}
async function downloadRecord(path,name){const response=await fetch('/admin/api'+path,{headers:{'X-Nath-Admin':'1'},signal:AbortSignal.timeout(30000)});if(!response.ok){let message='Download failed. Sign in again and retry.';try{message=(await response.json()).error||message;}catch{}throw Error(message);}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('#export-page').addEventListener('click',event=>{const button=event.currentTarget;button.disabled=true;action(()=>downloadRecord(`/exports/requests.csv?q=${encodeURIComponent(exportQuery.q)}&status=${encodeURIComponent(exportQuery.status)}&page=${exportQuery.page}`,`nath-requests-page-${page+1}.csv`)).finally(()=>button.disabled=false);});
$('#export-record').addEventListener('click',event=>{if(!current)return;const button=event.currentTarget;button.disabled=true;action(()=>downloadRecord('/exports/'+current.reference+'.json',current.reference+'.json')).finally(()=>button.disabled=false);});
