const $=s=>document.querySelector(s),notice=$('#admin-notice');
let page=0,current=null,services=[],exportQuery={q:"",status:"",page:0};
const nepalTime=value=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kathmandu',dateStyle:'medium',timeStyle:'short'}).format(new Date(value.includes('T')?value:value.replace(' ','T')+'Z'))+' NPT';
const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;};
async function api(path,method='GET',body,draftForm=null){const draftSnapshot=NathDrafts.snapshot(draftForm?[draftForm]:[]);const response=await fetch('/admin/api'+path,{method,headers:{'Content-Type':'application/json','X-Nath-Admin':'1'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});let data;try{data=await response.json();}catch{throw Error('Please sign in again or ask the owner to finish admin setup.');}if(!response.ok)throw Error(data.error||'Unable to complete this action');NathDrafts.saved(draftSnapshot);return data;}
async function action(fn){notice.textContent='Working…';try{await fn();notice.textContent='Ready';}catch(e){notice.textContent=e.message;notice.focus();}}
async function overview(){const {counts}=await api('/overview');const box=$('#overview');box.replaceChildren();for(const [key,label] of [['new','New'],['contacted','Contacted'],['in_progress','In progress'],['closed','Closed']]){const card=text('button','','overview-card');card.type='button';card.setAttribute('aria-label',`Show ${label.toLowerCase()} requests: ${counts[key]||0}`);card.setAttribute('aria-pressed',String($('#request-status').value===key));card.append(text('strong',String(counts[key]||0)),text('span',label),text('small','View requests →'));card.addEventListener('click',()=>{page=0;$('#request-query').value='';$('#request-status').value=key;$('#request-work').value='';action(async()=>{await requests();$('#request-status').focus();$('#requests').scrollIntoView({block:'start'});});});box.append(card);}}
async function requests(){await overview();await attention();await retention();await followUps();const q=$('#request-query').value.trim(),status=$('#request-status').value,work=$('#request-work').value;const data=await api(`/requests?q=${encodeURIComponent(q)}&status=${status}&work=${work}&page=${page}`);exportQuery={q,status,work,page};document.querySelectorAll('[data-work]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.work===work&&!q&&!status)));const list=$('#request-list');list.replaceChildren();if(!data.requests.length)list.append(text('p','No matching requests.'));
 for(const r of data.requests){const card=text('article','','request-row');const button=text('button',r.reference,'text-link');button.type='button';button.addEventListener('click',()=>action(()=>detail(r.reference)));card.append(button,text('strong',r.name),text('span',r.phone),text('span',`${r.status.replaceAll('_',' ')}${r.outcome?' · '+r.outcome:''}${r.waiting_customer&&r.status!=='closed'?' · Waiting for customer':r.last_message_sender==='customer'?' · Customer replied':''}`),text('small',nepalTime(r.created_at)));list.append(card);}
 $('#previous-page').disabled=page===0;$('#next-page').disabled=!data.hasMore;$('#page-number').textContent=`Page ${page+1}`;
}
async function detail(reference){const draftIds=['request-edit','message-form','finance-form'];if(!NathDrafts.confirmDiscard(draftIds))return;const d=await api('/requests/'+reference);NathDrafts.clear(draftIds);const changedRequest=current?.reference!==d.record.reference;current=d.record;if(changedRequest)selectRequestTab(0);const box=$('#request-detail');box.hidden=false;$('#detail-reference').textContent=reference;$('#detail-name').textContent=current.name+' · '+current.phone;$('#detail-service').textContent=current.service_title||current.service_id||current.service;$('#detail-message').textContent=current.message;$('#detail-created').textContent='Submitted '+nepalTime(current.created_at);$('#edit-status').value=current.status;$('#edit-outcome').value=current.outcome;$('#internal-note').value=current.internal_note;$('#detail-callback').textContent='Callback preference: '+({morning:'9 AM–12 PM',afternoon:'12 PM–3 PM',late:'3 PM–6 PM'}[current.callback_window]||'No preference')+' · Sun–Fri, Nepal time (not a confirmed appointment)';$('#follow-up-at').value=current.follow_up_at?new Date(Date.parse(current.follow_up_at.replace(' ','T')+'Z')+20700000).toISOString().slice(0,16):'';const history=$('#request-history');history.replaceChildren();for(const event of d.events)history.append(text('li',`${nepalTime(event.created_at)} · ${event.from_status} → ${event.to_status}${event.outcome?' / '+event.outcome:''} · ${event.actor}`));await loadConversation(reference);await loadFinance(reference);box.scrollIntoView({behavior:'smooth',block:'start'});$('#detail-reference').focus();}
$('#request-search').addEventListener('submit',e=>{e.preventDefault();page=0;action(requests);});
$('#previous-page').addEventListener('click',()=>{page--;action(requests);});$('#next-page').addEventListener('click',()=>{page++;action(requests);});
$('#request-edit').addEventListener('submit',e=>{e.preventDefault();if(!current)return;const button=e.submitter;button.disabled=true;action(async()=>{await api('/requests/'+current.reference,'PATCH',{version:current.version,status:$('#edit-status').value,outcome:$('#edit-status').value==='closed'?$('#edit-outcome').value:'',internal_note:$('#internal-note').value,follow_up_at:$('#follow-up-at').value?new Date($('#follow-up-at').value+':00+05:45').toISOString():null},'request-edit');await detail(current.reference);await requests();}).finally(()=>button.disabled=false);});
$('#edit-status').addEventListener('change',()=>{$('#edit-outcome').required=$('#edit-status').value==='closed';});
async function loadServices(){const data=await api('/services');services=data.services;renderServices();}
function renderServices(){const query=$('#service-search').value.trim().toLowerCase(),visibility=$('#service-visibility').value;const filtered=services.filter(s=>(s.title_en+' '+s.title_ne).toLowerCase().includes(query)&&(visibility==='all'||(visibility==='visible'?s.active:!s.active)));$('#service-count').textContent=filtered.length+' services shown';const list=$('#admin-services');list.replaceChildren();for(const s of filtered){const card=text('article','','request-row');card.append(text('strong',s.title_en),text('span',s.active?({available:'Available',paused:'Temporarily unavailable',soon:'Coming soon'}[s.availability]||'Available'):'Removed / hidden'),text('span',`From Rs. ${s.starting_price}`));const edit=text('button','Edit','button secondary');edit.type='button';edit.addEventListener('click',()=>editService(s));const duplicate=text('button','Duplicate as draft','button secondary');duplicate.type='button';duplicate.addEventListener('click',()=>{if(editService({...s,id:'',version:0,active:false})===false)return;NathDrafts.mark('service-edit');$('#service-edit').elements.id.readOnly=false;$('#service-edit').elements.id.focus();notice.textContent='Draft copy: choose a new web address, review both languages and save. It stays hidden until you make it visible.';});card.append(edit,duplicate);if(s.active){const remove=text('button','Remove from website','button secondary');remove.type='button';remove.addEventListener('click',()=>{if(confirm('Remove this service from the public catalogue? Existing requests will remain available.'))action(async()=>{await api('/services/'+s.id,'DELETE',{version:s.version});await loadServices();});});card.append(remove);}else{const restore=text('button','Restore service','button secondary');restore.type='button';restore.addEventListener('click',()=>action(async()=>{await api('/services','POST',{...s,items:JSON.parse(s.items_json),active:true});await loadServices();}));card.append(restore);}list.append(card);}}
function editService(s){if(!NathDrafts.confirmDiscard(['service-edit']))return false;NathDrafts.clear(['service-edit']);const form=$('#service-edit');form.reset();form.hidden=false;$('#service-preview').hidden=true;for(const k of ['id','category','icon','title_en','title_ne','description_en','description_ne','note_en','note_ne','starting_price','availability','sort_order'])form.elements[k].value=s?.[k]??(k==='sort_order'?0:k==='starting_price'?100:k==='availability'?'available':'');form.elements.version.value=s?.version||0;form.elements.id.readOnly=!!s;form.elements.active.checked=s?!!s.active:true;const items=s?JSON.parse(s.items_json):[];form.elements.items_en.value=items.map(x=>x[0]).join('\n');form.elements.items_ne.value=items.map(x=>x[1]).join('\n');form.scrollIntoView({behavior:'smooth',block:'start'});form.elements.title_en.focus();}
$('#add-service').addEventListener('click',()=>editService(null));
$('#service-edit').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const d=Object.fromEntries(new FormData(form));const en=d.items_en.split('\n').map(x=>x.trim()).filter(Boolean),ne=d.items_ne.split('\n').map(x=>x.trim()).filter(Boolean);if(en.length!==ne.length){notice.textContent='Enter the same number of English and Nepali service items.';return;}d.items=en.map((x,i)=>[x,ne[i]]);d.version=Number(d.version);d.starting_price=Number(d.starting_price);d.sort_order=Number(d.sort_order);d.active=form.elements.active.checked;const button=e.submitter;button.disabled=true;action(async()=>{await api('/services','POST',d,'service-edit');form.hidden=true;await loadServices();}).finally(()=>button.disabled=false);});
action(async()=>{const me=await api('/me');$('#admin-email').textContent=me.email;await requests();await loadServices();await loadReplyTemplates();await loadWebsiteContent();});

document.querySelector('#sign-out').addEventListener('click',()=>action(async()=>{const r=await fetch('/admin/auth/logout',{method:'POST',headers:{'Content-Type':'application/json','X-Nath-Admin':'1'},body:'{}'});if(!r.ok)throw Error('Unable to sign out. Try again.');location.replace('/admin/login');}));

$('#service-search').addEventListener('input',renderServices);
$('#service-visibility').addEventListener('change',renderServices);
$('#cancel-service').addEventListener('click',()=>{$('#service-edit').hidden=true;$('#add-service').focus();});

let financeRecord=null;
const money=p=>new Intl.NumberFormat('en-NP',{style:'currency',currency:'NPR'}).format(p/100);
function quoteRow(item={description:'',kind:'service',paisa:0}){
 const row=text('div','','quote-row');
 const description=document.createElement('input');description.value=item.description;description.placeholder='Charge description';description.setAttribute('aria-label','Charge description');description.maxLength=160;description.required=true;
 const kind=document.createElement('select');kind.setAttribute('aria-label','Charge type');for(const [value,label] of [['service','Nath service charge'],['provider','Official / provider fee']]){const option=text('option',label);option.value=value;kind.append(option);}kind.value=item.kind;
 const amount=document.createElement('input');amount.type='number';amount.min='0';amount.max='1000000';amount.step='0.01';amount.required=true;amount.value=(item.paisa/100).toFixed(2);amount.setAttribute('aria-label','Amount in NPR');
 const remove=text('button','Remove','button secondary');remove.type='button';remove.addEventListener('click',()=>{row.remove();NathDrafts.mark('finance-form');quoteTotal();});row.append(description,kind,amount,remove);amount.addEventListener('input',quoteTotal);$('#quote-items').append(row);
}
function quoteItems(){return [...$('#quote-items').children].map(row=>({description:row.children[0].value,kind:row.children[1].value,paisa:Math.round(Number(row.children[2].value)*100)}));}
function quoteTotal(){const total=quoteItems().reduce((n,x)=>n+x.paisa,0),paid=Math.round(Number($('#paid-total').value)*100);$('#quote-total').textContent=`Quote: ${money(total)} · Received: ${money(paid)} · Balance: ${money(total-paid)} · ${paid===0?'Unpaid':paid<total?'Partially paid':paid===total?'Paid':'Check overpayment'}`;}
async function loadFinance(reference){if(!NathDrafts.confirmDiscard(['finance-form']))return;NathDrafts.clear(['finance-form']);financeRecord=await api('/requests/'+reference+'/finance');$('#quote-items').replaceChildren();for(const item of financeRecord.items)quoteRow(item);if(!financeRecord.items.length)quoteRow();$('#quote-shared').checked=financeRecord.quote_shared;$('#payment-instructions').value=financeRecord.payment_instructions||'';$('#quote-acceptance').textContent=financeRecord.accepted_revision===financeRecord.quote_revision&&financeRecord.accepted_at?'Customer accepted this quote: '+nepalTime(financeRecord.accepted_at):'Current quote not accepted';$('#paid-total').value=(financeRecord.paid_paisa/100).toFixed(2);$('#payment-note').value='';quoteTotal();$('#print-quote').disabled=!financeRecord.items.length;const history=$('#finance-history');history.replaceChildren();for(const e of financeRecord.history)history.append(text('li',`${nepalTime(e.created_at)} · Quote ${money(JSON.parse(e.quote_json).reduce((n,x)=>n+x.paisa,0))} · Received ${money(e.paid_paisa)} · ${e.payment_note}`));}
$('#quote-add').addEventListener('click',()=>{if($('#quote-items').children.length>=20){notice.textContent='Maximum 20 charges per quote.';return;}quoteRow();NathDrafts.mark('finance-form');});
$('#paid-total').addEventListener('input',quoteTotal);
$('#finance-form').addEventListener('submit',event=>{event.preventDefault();if(!current||!financeRecord)return;const button=event.submitter;button.disabled=true;action(async()=>{await api('/requests/'+current.reference+'/finance','PATCH',{version:financeRecord.version,quote_shared:$('#quote-shared').checked,payment_instructions:$('#payment-instructions').value,items:quoteItems(),paid_paisa:Math.round(Number($('#paid-total').value)*100),payment_note:$('#payment-note').value},'finance-form');await loadFinance(current.reference);}).finally(()=>button.disabled=false);});
$('#print-quote').addEventListener('click',()=>{if(!financeRecord?.items.length)return;let sheet=$('#print-sheet');if(!sheet){sheet=text('section','','print-sheet');sheet.id='print-sheet';document.body.append(sheet);}sheet.replaceChildren(text('h1','Nath Online Services — Quote'),text('p','Butwal, Nepal · +977 9867302353'),text('p',current.reference),text('p',current.name));for(const item of financeRecord.items)sheet.append(text('p',`${item.description} (${item.kind==='service'?'Service charge':'Official / provider fee'}) — ${money(item.paisa)}`));const total=financeRecord.items.reduce((n,x)=>n+x.paisa,0);sheet.append(text('strong',`Total: ${money(total)}`),text('p',`Recorded received: ${money(financeRecord.paid_paisa)} · Balance: ${money(total-financeRecord.paid_paisa)}`),text('p','Subject to customer approval. This quote is not a tax invoice or proof of payment.'));window.print();});

async function retention(){const data=await api('/retention');$('#retention-summary').textContent=`Closed requests and their linked quote/payment history are deleted after ${data.days} days. ${data.due_soon} reach that age within seven days; ${data.eligible} are eligible for the next cleanup. Open requests are kept.`;}
async function downloadRecord(path,name){const response=await fetch('/admin/api'+path,{headers:{'X-Nath-Admin':'1'},signal:AbortSignal.timeout(30000)});if(!response.ok){let message='Download failed. Sign in again and retry.';try{message=(await response.json()).error||message;}catch{}throw Error(message);}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('#export-page').addEventListener('click',event=>{const button=event.currentTarget;button.disabled=true;action(()=>downloadRecord(`/exports/requests.csv?q=${encodeURIComponent(exportQuery.q)}&status=${encodeURIComponent(exportQuery.status)}&work=${encodeURIComponent(exportQuery.work||'')}&page=${exportQuery.page}`,`nath-requests-page-${page+1}.csv`)).finally(()=>button.disabled=false);});
$('#export-record').addEventListener('click',event=>{if(!current)return;const button=event.currentTarget;button.disabled=true;action(()=>downloadRecord('/exports/'+current.reference+'.json',current.reference+'.json')).finally(()=>button.disabled=false);});

let websiteContent=[];
async function loadWebsiteContent(){if(!NathDrafts.confirmDiscard(['website-content-form']))return;NathDrafts.clear(['website-content-form']);websiteContent=(await api('/website-content')).content;const select=$('#content-id'),selected=select.value;select.replaceChildren();const review=text('option','Customer review');review.value='review';select.append(review);const home=text('option','Homepage headline and introduction');home.value='home';select.append(home);for(const [id,title] of [['announcement','Website announcement'],['featured','Featured homepage services']]){const option=text('option',title);option.value=id;select.append(option);}for(const service of services){const option=text('option',service.title_en+' — checklist and timing');option.value='service:'+service.id;select.append(option);}select.value=selected||'review';renderWebsiteContent();}
function renderWebsiteContent(){$('#content-preview').hidden=true;const id=$('#content-id').value,row=websiteContent.find(x=>x.id===id),data=row?JSON.parse(row.data_json):{};const fields=id==='announcement'?{text_en:'Announcement in English',text_ne:'Announcement in Nepali'}:id==='featured'?{}:id==='home'?{title_en:'Homepage headline in English',title_ne:'Homepage headline in Nepali',intro_en:'Introduction in English',intro_ne:'Introduction in Nepali'}:id==='review'?{name:'Customer display name',text_en:'Review in English',text_ne:'Review in Nepali'}:{checklist_en:'Checklist in English (one item per line)',checklist_ne:'Checklist in Nepali (one item per line)',timeline_en:'Confirmed timing estimate in English',timeline_ne:'Confirmed timing estimate in Nepali',questions_en:'Request guidance in English',questions_ne:'Request guidance in Nepali'};const container=$('#content-fields');container.replaceChildren();for(const [key,title] of Object.entries(fields)){const label=text('label',title),input=document.createElement('textarea');input.name=key;input.maxLength=1200;input.value=data[key]||'';label.append(input);container.append(label);}if(id==='announcement'){container.append(text('p','Schedule in Nepal time. Leave start blank to show immediately; leave expiry blank to keep showing until unpublished.'));for(const [key,title] of [['starts_at','Start (Nepal time)'],['ends_at','Expiry (Nepal time)']]){const label=text('label',title),input=document.createElement('input');input.type='datetime-local';input.name=key;input.min='2020-01-01T00:00';input.max='2099-12-31T23:59';input.value=data[key]?new Date(Date.parse(data[key])+20700000).toISOString().slice(0,16):'';label.append(input);container.append(label);}}if(id==='featured'){const hidden=document.createElement('input');hidden.type='hidden';hidden.name='service_ids';hidden.value=data.service_ids||'';container.append(hidden,text('p','Choose up to three visible services. Unavailable services are automatically omitted from the homepage.'));const selected=new Set(hidden.value.split(','));for(const service of services.filter(s=>s.active)){const label=text('label',service.title_en,'check-label'),check=document.createElement('input');check.type='checkbox';check.value=service.id;check.checked=selected.has(service.id);check.addEventListener('change',()=>{const checked=[...container.querySelectorAll('input[type=checkbox]:checked')];if(checked.length>3){check.checked=false;notice.textContent='Choose up to three featured services.';return;}hidden.value=checked.map(c=>c.value).join(',');});label.prepend(check);container.append(label);}}$('#content-confirmed').checked=!!data.confirmed;$('#content-published').checked=!!data.published;}
let previousContentId=$('#content-id').value;$('#content-id').addEventListener('focus',()=>previousContentId=$('#content-id').value);$('#content-id').addEventListener('change',()=>{if(!NathDrafts.confirmDiscard(['website-content-form'])){$('#content-id').value=previousContentId;return;}NathDrafts.clear(['website-content-form']);renderWebsiteContent();previousContentId=$('#content-id').value;});
$('#website-content-form').addEventListener('submit',event=>{event.preventDefault();const id=$('#content-id').value,row=websiteContent.find(x=>x.id===id),content=Object.fromEntries(new FormData(event.currentTarget));if(id==='announcement')for(const key of ['starts_at','ends_at'])content[key]=content[key]?new Date(content[key]+':00+05:45').toISOString():'';content.confirmed=$('#content-confirmed').checked;content.published=$('#content-published').checked;const button=event.submitter;button.disabled=true;action(async()=>{await api('/website-content','POST',{id,version:row?.version||0,content},'website-content-form');await loadWebsiteContent();}).finally(()=>button.disabled=false);});

async function followUps(){const data=await api('/follow-ups'),box=$('#follow-ups');box.replaceChildren();if(!data.reminders.length)box.append(text('p','No follow-ups due in the next 24 hours.'));for(const r of data.reminders){const item=text('p',''),button=text('button',r.reference,'text-link');button.type='button';button.addEventListener('click',()=>action(()=>detail(r.reference)));item.append(button,text('span',' · '+nepalTime(r.follow_up_at)+(Date.parse(r.follow_up_at.replace(' ','T')+'Z')<=Date.now()?' · Due now':'')));box.append(item);}if(data.hasMore)box.append(text('p','Showing the earliest 50. Clear completed reminders to see more.'));}
$('#refresh-followups').addEventListener('click',()=>action(followUps));

let conversationRecord=null,messageKey=null,messageAttempt=null;
async function loadConversation(reference){conversationRecord=await api('/requests/'+reference+'/messages');messageKey=crypto.randomUUID();messageAttempt=null;$('#message-form').reset();renderReplyChoices();$('#message-form').hidden=current.status==='closed';$('#conversation-state').textContent=conversationRecord.waiting?'Waiting for customer reply':'No customer reply requested';const list=$('#conversation-history');list.replaceChildren();if(conversationRecord.hasMore)list.append(text('li','Latest 50 messages shown. Download the detailed record for older messages.'));for(const m of conversationRecord.messages)list.append(text('li',`${m.sender==='team'?'Nath team':'Customer'} · ${nepalTime(m.created_at)}\n${m.body}`,'preserve-lines'));}
let replyTemplates=[];
function renderReplyChoices(){const select=$('#reply-template'),category=services.find(s=>s.id===current?.service_id)?.category;select.replaceChildren(new Option('Write your own',''));for(const template of replyTemplates.filter(t=>t.active&&(!category||t.category==='all'||t.category===category)))select.append(new Option(template.title,template.id));}
async function loadReplyTemplates(){replyTemplates=(await api('/reply-templates')).templates;renderReplyChoices();const list=$('#template-list');list.replaceChildren();for(const template of replyTemplates){const card=text('article','','request-row'),edit=text('button','Edit','button secondary'),visibility=text('button',template.active?'Hide template':'Restore template','button secondary');edit.type=visibility.type='button';edit.addEventListener('click',()=>editReplyTemplate(template));visibility.addEventListener('click',()=>action(async()=>{await api('/reply-templates','POST',{version:template.version,template:{...template,active:!template.active}});await loadReplyTemplates();}));card.append(text('strong',template.title),text('span',template.category==='all'?'All services':template.category),text('span',template.active?'Available':'Hidden'),edit,visibility);list.append(card);}}
function editReplyTemplate(template){if(!NathDrafts.confirmDiscard(['template-editor']))return;NathDrafts.clear(['template-editor']);const form=$('#template-editor');form.reset();form.hidden=false;for(const key of ['id','title','body','category','version'])form.elements[key].value=template?.[key]??({id:'reply-'+crypto.randomUUID(),category:'all',version:0}[key]??'');form.elements.waiting.checked=!!template?.waiting;form.elements.active.checked=template?template.active:true;form.elements.title.focus();form.scrollIntoView({block:'start'});}
$('#add-template').addEventListener('click',()=>editReplyTemplate(null));
$('#cancel-template').addEventListener('click',()=>{$('#template-editor').hidden=true;$('#add-template').focus();});
$('#reload-templates').addEventListener('click',()=>action(loadReplyTemplates));
$('#template-editor').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form)),version=Number(data.version);data.active=form.elements.active.checked;data.waiting=form.elements.waiting.checked;const button=event.submitter;button.disabled=true;action(async()=>{await api('/reply-templates','POST',{version,template:data},'template-editor');form.hidden=true;await loadReplyTemplates();}).finally(()=>button.disabled=false);});
$('#reply-template').addEventListener('change',()=>{const template=replyTemplates.find(t=>t.id===$('#reply-template').value);if(!template)return;if($('#team-message').value&&!confirm('Replace the current draft with this template?'))return;$('#team-message').value=template.body;NathDrafts.mark('message-form');$('#waiting-customer').checked=template.waiting;$('#team-message').focus();});
$('#message-form').addEventListener('submit',event=>{event.preventDefault();if(!current||!conversationRecord)return;const button=event.submitter;const payload={message:$('#team-message').value.trim(),waiting:$('#waiting-customer').checked,version:conversationRecord.version,key:messageKey};if(messageAttempt&&JSON.stringify(payload)!==messageAttempt){notice.textContent='Previous result is uncertain. Reopen the request before changing the draft.';return;}messageAttempt=JSON.stringify(payload);button.disabled=true;action(async()=>{await api('/requests/'+current.reference+'/messages','POST',payload,'message-form');await detail(current.reference);await requests();}).finally(()=>button.disabled=false);});

async function attention(){const data=await api('/attention'),box=$('#attention-list');box.replaceChildren();if(!data.requests.length)box.append(text('p','You are up to date. No requests need attention.'));for(const r of data.requests){const item=text('p',''),button=text('button',r.reference,'text-link');button.type='button';button.addEventListener('click',()=>action(()=>detail(r.reference)));const reasons=[];if(r.follow_up_at&&Date.parse(r.follow_up_at.replace(' ','T')+'Z')<=Date.now())reasons.push('Follow-up overdue');if(r.last_sender==='customer')reasons.push('Customer replied');if(r.status==='new')reasons.push('New request');item.append(button,text('span',' · '+reasons.join(' · ')));box.append(item);}if(data.hasMore)box.append(text('p','Showing the first 50. Resolve these requests to see more.'));}
$('#preview-content').addEventListener('click',()=>{const box=$('#content-preview');box.replaceChildren(text('h3','Text preview — not saved or published'));for(const field of $('#content-fields').querySelectorAll('textarea')){box.append(text('h4',field.previousSibling?.textContent||field.name),text('p',field.value||'(Empty)','preserve-lines'));}if($('#content-id').value==='featured'){const selected=[...$('#content-fields').querySelectorAll('input[type=checkbox]:checked')];box.append(text('p',selected.map(c=>c.parentElement.textContent).join(' · ')||'No services selected'));}box.hidden=false;});
$('#website-content-form').addEventListener('input',()=>{$('#content-preview').hidden=true;});

$('#preview-service').addEventListener('click',()=>{const form=$('#service-edit'),box=$('#service-preview');box.replaceChildren(text('p','Text preview — unsaved changes.'));for(const [lang,label] of [['en','English'],['ne','नेपाली']]){const panel=text('section','');panel.lang=lang;panel.append(text('h3',label),text('h4',form.elements['title_'+lang].value),text('p',form.elements['description_'+lang].value),text('p',form.elements['note_'+lang].value));const list=text('ul','');for(const item of form.elements['items_'+lang].value.split('\n').filter(x=>x.trim()))list.append(text('li',item));panel.append(list);box.append(panel);}box.append(text('p','From NPR '+form.elements.starting_price.value+' · '+(form.elements.active.checked?'Visible when saved':'Hidden draft')));box.hidden=false;});
$('#service-edit').addEventListener('input',()=>{$('#service-preview').hidden=true;});

document.querySelectorAll('[data-work]').forEach(button=>button.addEventListener('click',()=>{page=0;$('#request-query').value='';$('#request-status').value='';$('#request-work').value=button.dataset.work;action(requests);}));

// Keep form nodes in place within accessible panels so switching tabs preserves drafts.
const detailBox=$('#request-detail');
const detailTabs=document.createElement('div');detailTabs.className='detail-tabs';detailTabs.setAttribute('role','tablist');detailTabs.setAttribute('aria-label','Request workspace');
const statusPanel=document.createElement('section');statusPanel.id='status-panel';$('#request-edit').before(statusPanel);statusPanel.append($('#request-edit'));
const historyPanel=document.createElement('section');historyPanel.id='history-panel';const historyHeading=$('#request-history').previousElementSibling;historyHeading.before(historyPanel);historyPanel.append(historyHeading,$('#request-history'));
const workspacePanels=[['status-panel','Status & notes'],['conversation-panel','Messages'],['finance-panel','Quote & payments'],['history-panel','History']];
statusPanel.before(detailTabs);
function selectRequestTab(index,focus=false){workspacePanels.forEach(([id],i)=>{const tab=detailTabs.children[i];tab.setAttribute('aria-selected',String(i===index));tab.tabIndex=i===index?0:-1;document.getElementById(id).hidden=i!==index;});if(focus)detailTabs.children[index].focus();}
workspacePanels.forEach(([id,label],index)=>{const panel=document.getElementById(id),button=text('button',label,'button secondary');button.type='button';button.id='tab-'+id;button.setAttribute('role','tab');button.setAttribute('aria-controls',id);panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',button.id);panel.tabIndex=0;button.addEventListener('click',()=>selectRequestTab(index));button.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%4;else if(event.key==='ArrowLeft')next=(index+3)%4;else if(event.key==='Home')next=0;else if(event.key==='End')next=3;else return;event.preventDefault();selectRequestTab(next,true);});detailTabs.append(button);});
selectRequestTab(0);

let suggestionPage=0;
async function loadSuggestions(){const data=await api('/suggestions?status='+$('#suggestion-status').value+'&page='+suggestionPage),list=$('#suggestion-list');list.replaceChildren();if(!data.suggestions.length)list.append(text('p','No suggestions in this view.'));for(const item of data.suggestions){const card=text('article','','paper'),form=document.createElement('form');card.append(text('h3',item.category+' suggestion'),text('small',item.id+' · '+nepalTime(item.created_at)),text('p',item.message,'preserve-lines'),text('p',item.phone?'Requested contact: '+item.phone:'No response requested'));const status=document.createElement('select');for(const [value,label] of [['new','New'],['reviewing','Reviewing'],['planned','Planned'],['available','Available'],['not_proceeding','Not proceeding']])status.append(new Option(label,value));status.value=item.status;const note=document.createElement('textarea');note.maxLength=2000;note.value=item.note;const duplicate=document.createElement('input');duplicate.maxLength=36;duplicate.value=item.duplicate_of;for(const [name,control] of [['Review status',status],['Private notes',note],['Duplicate of suggestion ID (optional)',duplicate]]){const label=text('label',name);label.append(control);form.append(label);}const save=text('button','Save review','button');form.append(save);form.addEventListener('submit',event=>{event.preventDefault();save.disabled=true;action(async()=>{await api('/suggestions','POST',{id:item.id,version:item.version,status:status.value,note:note.value,duplicate_of:duplicate.value.trim()});await loadSuggestions();}).finally(()=>save.disabled=false);});const draft=text('button','Prepare hidden service draft','button secondary');draft.type='button';draft.addEventListener('click',()=>{if(editService(null)===false)return;NathDrafts.mark('service-edit');const f=$('#service-edit');f.elements.active.checked=false;f.elements.description_en.value=item.message;f.elements.category.value='other';f.elements.icon.value='chat';notice.textContent='Unsaved hidden draft: add a title, Nepali translation, confirmed scope and charges before saving. Review customer text and remove private details.';});card.append(form,draft);list.append(card);}$('#suggestions-prev').disabled=suggestionPage===0;$('#suggestions-next').disabled=!data.hasMore;$('#suggestions-page').textContent='Page '+(suggestionPage+1);}
$('#reload-suggestions').addEventListener('click',()=>action(loadSuggestions));$('#suggestion-status').addEventListener('change',()=>{suggestionPage=0;action(loadSuggestions);});$('#suggestions-prev').addEventListener('click',()=>{suggestionPage--;action(loadSuggestions);});$('#suggestions-next').addEventListener('click',()=>{suggestionPage++;action(loadSuggestions);});
