export const services = [
 {id:'government',icon:'building',en:'Government & documents',ne:'सरकारी सेवा तथा कागजात',desc:['A little guidance for the important paperwork.','महत्त्वपूर्ण कागजी प्रक्रियामा सहज मार्गदर्शन।'],items:[['Passport application assistance','राहदानी आवेदन सहयोग'],['PAN registration guidance','PAN दर्ता मार्गदर्शन'],['Citizenship process guidance','नागरिकता प्रक्रियामा मार्गदर्शन'],['Voter registration & corrections','मतदाता दर्ता तथा विवरण सच्याउने सहयोग']],note:['Some services require your personal attendance, biometrics or original documents. We explain the official process; we cannot issue documents or guarantee approval.','केही सेवामा स्वयं उपस्थित हुनुपर्ने, बायोमेट्रिक वा सक्कल कागजात आवश्यक हुन सक्छ। हामी प्रक्रियामा सहयोग गर्छौँ; कागजात जारी गर्ने वा स्वीकृतिको ग्यारेन्टी गर्ने अधिकार हामीसँग छैन।']},
 {id:'utilities',icon:'bolt',en:'Bills & utility payments',ne:'बिल तथा उपयोगिता भुक्तानी',desc:['Keep everyday essentials running smoothly.','दैनिक आवश्यक सेवाको भुक्तानी सहज बनाउनुहोस्।'],items:[['Electricity bill assistance','विद्युत् बिल भुक्तानी सहयोग'],['Water bill assistance','खानेपानी बिल भुक्तानी सहयोग'],['Internet & broadband bills','इन्टरनेट तथा ब्रोडब्यान्ड बिल']],note:['We confirm your provider, bill details and total amount before processing. Never share a bank PIN, password or OTP.','भुक्तानीअघि सेवा प्रदायक, बिल विवरण र कुल रकम पुष्टि गरिन्छ। बैंक PIN, पासवर्ड वा OTP नदिनुहोस्।']},
 {id:'travel',icon:'ticket',en:'Tickets & travel',ne:'टिकट तथा यात्रा',desc:['Help planning your next journey, near or far.','नजिक वा टाढाको यात्राको तयारीमा सहयोग।'],items:[['Bus ticket booking','बस टिकट बुकिङ'],['Airline booking assistance','हवाई टिकट बुकिङ सहयोग'],['Event tickets','कार्यक्रमका टिकट'],['Train booking enquiries','रेल टिकटसम्बन्धी जानकारी']],note:['Availability, fares, routes, cancellation terms and identity requirements depend on the operator. Tickets are confirmed only after the provider confirms the booking.','टिकट उपलब्धता, भाडा, रुट, रद्द गर्ने नियम र परिचयपत्रको आवश्यकता सम्बन्धित प्रदायकमा निर्भर हुन्छ। प्रदायकको पुष्टि भएपछि मात्र बुकिङ निश्चित हुन्छ।']},
 {id:'banking',icon:'wallet',en:'Banking & wallet guidance',ne:'बैंकिङ तथा वालेट मार्गदर्शन',desc:['Understand the steps. Stay in control of your money.','प्रक्रिया बुझ्नुहोस्। आफ्नो रकमको नियन्त्रण आफैँ राख्नुहोस्।'],items:[['Mobile banking setup guidance','मोबाइल बैंकिङ सेटअप मार्गदर्शन'],['Digital wallet setup','डिजिटल वालेट सेटअप'],['Bank account opening guidance','बैंक खाता खोल्ने मार्गदर्शन'],['Remittance process assistance','रेमिट्यान्स प्रक्रियामा सहयोग']],note:['Guidance only; we are not a bank or investment adviser. Complete sensitive authentication yourself through your provider. We never request passwords, PINs or OTPs.','हामी मार्गदर्शन गर्छौँ; बैंक वा लगानी सल्लाहकार होइनौँ। संवेदनशील प्रमाणीकरण सम्बन्धित प्रदायकमार्फत आफैँ गर्नुहोस्। हामी पासवर्ड, PIN वा OTP माग्दैनौँ।']},
 {id:'education',icon:'book',en:'Education & applications',ne:'शिक्षा तथा आवेदन',desc:['Give your next opportunity a confident start.','नयाँ अवसरका लागि आत्मविश्वासका साथ तयारी गर्नुहोस्।'],items:[['School & college admissions','विद्यालय तथा कलेज भर्ना'],['Scholarship applications','छात्रवृत्ति आवेदन'],['SEE / NEB form assistance','SEE / NEB फाराम सहयोग'],['University application guidance','विश्वविद्यालय आवेदन मार्गदर्शन']],note:['Eligibility, deadlines, supporting documents and decisions are set by the institution. You review and confirm all information before submission.','योग्यता, समयसीमा, आवश्यक कागजात र निर्णय सम्बन्धित संस्थाले तय गर्छ। आवेदनअघि सबै विवरण तपाईंले जाँचेर पुष्टि गर्नुहुन्छ।']},
 {id:'other',icon:'chat',en:'Something else?',ne:'अन्य सहयोग चाहिएको छ?',desc:['Tell us what you need. We will check how we can help.','आफ्नो आवश्यकता बताउनुहोस्। सहयोग गर्न सकिन्छ कि जाँच गर्छौँ।'],items:[['Other online forms','अन्य अनलाइन फाराम'],['Portal registration guidance','पोर्टल दर्ता मार्गदर्शन'],['Help understanding a process','प्रक्रिया बुझ्न सहयोग']],note:['Our team confirms whether your request is supported before accepting work. We do not assist with false documents, fraud or unlawful applications.','काम स्वीकार गर्नुअघि सेवा उपलब्ध छ कि टोलीले पुष्टि गर्छ। नक्कली कागजात, ठगी वा गैरकानुनी आवेदनमा सहयोग गरिँदैन।']}
];
export const faq = [
 ['How do I request a service?','सेवा अनुरोध कसरी गर्ने?','Choose a service and send a short request, or contact us by phone or WhatsApp. Our team confirms availability, requirements and charges before work begins.','सेवा छानेर छोटो अनुरोध पठाउनुहोस् वा फोन/WhatsApp मा सम्पर्क गर्नुहोस्। काम सुरु गर्नुअघि उपलब्धता, आवश्यक विवरण र शुल्क पुष्टि गरिन्छ।'],
 ['Can everything be completed from home?','के सबै काम घरबाटै हुन्छ?','Many steps can be supported remotely. Some authorities require personal attendance, biometrics or original documents. We will explain these requirements before you proceed.','धेरै चरणमा टाढाबाट सहयोग गर्न सकिन्छ। केही निकायले स्वयं उपस्थित हुनुपर्ने, बायोमेट्रिक वा सक्कल कागजात माग्न सक्छन्। अगाडि बढ्नुअघि हामी स्पष्ट जानकारी दिन्छौँ।'],
 ['How much will it cost?','शुल्क कति लाग्छ?','Charges depend on the service. We explain the Nath service charge and any separate provider or official fees before you approve the work. No work starts on an unapproved quote.','शुल्क सेवाअनुसार फरक हुन्छ। तपाईंको स्वीकृतिअघि नाथको सेवा शुल्क र प्रदायक वा सरकारी शुल्क छुट्टाछुट्टै स्पष्ट गरिन्छ। स्वीकृति नभएको शुल्कमा काम सुरु हुँदैन।'],
 ['When will I hear back?','जवाफ कहिले आउँछ?','Our working hours are Sunday–Friday, 9:00 AM–6:00 PM Nepal time. We review requests during these hours. For urgent matters outside these hours, contact the Founder on WhatsApp.','हाम्रो समय आइतबार–शुक्रबार बिहान ९ देखि साँझ ६ बजेसम्म (नेपाल समय) हो। यस समयमा अनुरोध समीक्षा गरिन्छ। बाहिरको अत्यावश्यक काममा संस्थापकलाई WhatsApp गर्नुहोस्।'],
 ['Should I upload my documents here?','के यहाँ कागजात अपलोड गर्ने?','No. This initial request needs only your name, mobile number and a brief description. Our team will explain the necessary documents and appropriate sharing method later. Never send passwords, PINs or OTPs.','पर्दैन। प्रारम्भिक अनुरोधमा नाम, मोबाइल नम्बर र छोटो विवरण मात्र चाहिन्छ। आवश्यक कागजात र पठाउने उपयुक्त तरिका टोलीले पछि बताउँछ। पासवर्ड, PIN वा OTP नपठाउनुहोस्।'],
 ['Which payment methods are available?','भुक्तानीका माध्यम के हुन्?','We support eSewa, bank transfer, connectIPS, BHIM UPI and cash where applicable. Confirm availability and verified payment details with our team before paying.','उपयुक्त अवस्थामा eSewa, बैंक ट्रान्सफर, connectIPS, BHIM UPI र नगद स्वीकार गरिन्छ। रकम पठाउनुअघि उपलब्धता र आधिकारिक भुक्तानी विवरण टोलीसँग पुष्टि गर्नुहोस्।']
];
