// Progressive enhancements: no customer details are persisted in browser storage.
(()=>{
 const ne=document.documentElement.lang==='ne',t=(en,np)=>ne?np:en;
 const element=(tag,content,cls)=>{const node=document.createElement(tag);node.textContent=content;if(cls)node.className=cls;return node;};
 document.querySelector('#stop-motion')?.addEventListener('click',event=>{document.documentElement.dataset.motion='off';event.currentTarget.textContent=t('Animation off','एनिमेसन बन्द');event.currentTarget.disabled=true;});
 const finder=document.querySelector('#guided-finder');
 if(finder){
  const choices=[...document.querySelectorAll('[data-service]')].filter(card=>card.dataset.available!=='false').map(card=>{const link=card.querySelector('h3 a');let tasks=[];try{tasks=JSON.parse(card.dataset.tasks||'[]');}catch{}return {category:card.dataset.category,path:link?.getAttribute('href'),title:link?.textContent,tasks};}).filter(s=>s.path);
  const categories=[['government',t('Prepare an application or document','आवेदन वा कागजात तयार गर्ने')],['utilities',t('Pay a household bill','घरायसी बिल तिर्ने')],['travel',t('Plan travel or book a ticket','यात्रा योजना वा टिकट बुक गर्ने')],['banking',t('Get banking or wallet guidance','बैंक वा वालेटबारे सहयोग लिने')],['education',t('Apply for education or a scholarship','शिक्षा वा छात्रवृत्तिका लागि आवेदन दिने')],['other',t('Something else / not sure','अन्य काम / निश्चित छैन')]];
  const first=element('label',t('1. What would you like to do?','१. के गर्न चाहनुहुन्छ?')),goal=document.createElement('select');first.append(goal);goal.append(new Option(t('Choose your goal','आफ्नो काम छान्नुहोस्'),''));for(const [id,title] of categories)goal.append(new Option(title,id));
  const second=element('label',t('2. Which task best matches?','२. कुन काम मिल्छ?')),task=document.createElement('select');second.append(task);second.hidden=true;
  const result=element('div','','finder-result');result.hidden=true;result.setAttribute('aria-live','polite');
  let matches=[];
  function suggest(){result.replaceChildren();result.hidden=false;const match=matches[Number(task.value)];if(task.value===''||!match){const help=element('a',t('Describe your request','आफ्नो आवश्यकता बताउनुहोस्'),'button');help.href=(ne?'/ne':'')+'/request';result.append(element('p',t('Not sure? Tell our team what you need and we will check.','निश्चित छैन? आफ्नो आवश्यकता बताउनुहोस्, टोलीले जाँच गर्नेछ।')),help);return;}const {service,title}=match,id=service.path.split('/').pop();const links=element('div','','actions'),request=element('a',t('Continue with this task','यो काम लिएर अगाडि बढ्नुहोस्'),'button'),details=element('a',t('Read service details','सेवाको विवरण पढ्नुहोस्'),'text-link');request.href=(ne?'/ne':'')+'/request?'+new URLSearchParams({service:id,task:title});details.href=service.path;links.append(request,details);result.append(element('h3',title||service.title),element('p',t('We will confirm availability and the full charge before work begins.','कामअघि उपलब्धता र पूरा शुल्क पुष्टि गर्छौँ।')),links);}
  goal.addEventListener('change',()=>{result.hidden=true;task.replaceChildren();matches=[];second.hidden=!goal.value;if(!goal.value)return;task.append(new Option(t('Choose a task','काम छान्नुहोस्'),''));for(const service of choices.filter(s=>s.category===goal.value)){for(const title of service.tasks.length?service.tasks:[service.title]){const index=matches.push({service,title})-1;task.append(new Option(title+' — '+service.title,String(index)));}}task.append(new Option(t('Not listed / I need guidance','सूचीमा छैन / मार्गदर्शन चाहिन्छ'),''));if(!matches.length){second.hidden=true;suggest();}});
  task.addEventListener('change',suggest);finder.append(first,second,result);
  if(location.hash==='#choose-service'){finder.closest('details').open=true;goal.focus();}
 }
 const search=document.querySelector('#service-search');
 if(search){const shortcuts=element('div','','task-shortcuts');shortcuts.setAttribute('aria-label',t('Task shortcuts','कामका सर्टकट'));for(const [en,np] of [['Passport','राहदानी'],['PAN','PAN'],['Electricity','विद्युत्'],['Bus','बस'],['Scholarship','छात्रवृत्ति']]){const button=element('button',t(en,np),'button secondary');button.type='button';button.addEventListener('click',()=>{search.value=t(en,np);for(const id of ['category-filter','availability-filter']){const field=document.getElementById(id);if(field)field.value='';}search.dispatchEvent(new Event('input'));search.focus();});shortcuts.append(button);}search.after(shortcuts);}
 const form=document.querySelector('#request-form');if(!form)return;
 form.noValidate=true;if(new URLSearchParams(location.search).get('unlisted')==='1'){const note=element('p',t('Unlisted service — needs assessment. Describe your task and any deadline. We will check whether we can help before confirming availability or charges.','सूचीमा नभएको सेवा — समीक्षा आवश्यक। काम र समयसीमा बताउनुहोस्। उपलब्धता वा शुल्क पुष्टि गर्नुअघि सहयोग गर्न सकिन्छ कि जाँच गर्छौँ।'),'notice');form.before(note);}
 const submit=form.querySelector('button[type=submit]'),feedback=document.querySelector('#form-feedback');
 const groups=[['service','message'],['name','phone','callback_window'],['consent']];
 const titles=[t('Your service','चाहिएको सेवा'),t('Contact details','सम्पर्क विवरण'),t('Review and send','जाँचेर पठाउनुहोस्')];
 const sections=groups.map((names,index)=>{const fieldset=document.createElement('fieldset');fieldset.className='request-step';const legend=element('legend',titles[index]);fieldset.append(legend);for(const name of names){const control=form.elements[name];const label=control?.closest('label');if(label)fieldset.append(label);}form.insertBefore(fieldset,submit);return fieldset;});
 const taskLabel=element('label',t('Which task?','कुन काम?')),task=document.createElement('select');task.name='task_choice';taskLabel.append(task);sections[0].insertBefore(taskLabel,form.elements.message.closest('label'));
 const extra=document.createElement('details'),extraTitle=element('summary',t('Add helpful details (optional)','थप उपयोगी विवरण (ऐच्छिक)'));extra.className='optional-questions';extra.append(extraTitle);const questions=document.createElement('div');questions.className='task-questions';extra.append(questions);sections[0].insertBefore(extra,form.elements.message.closest('label'));extra.addEventListener('invalid',()=>{extra.open=true;},true);
 const taskDrafts=new Map();let previousService='';
 function rememberTask(){if(previousService)taskDrafts.set(previousService,{task:task.value,answers:[...questions.querySelectorAll('input')].map(input=>input.value)});}
 function taskQuestions(){questions.replaceChildren();const category=form.elements.service.selectedOptions[0]?.dataset.category;const fields=category==='travel'?[[t('Route or event (optional)','यात्राको स्थान वा कार्यक्रम (ऐच्छिक)'),'text'],[t('Preferred date (optional)','मनपर्ने मिति (ऐच्छिक)'),'date'],[t('Number of travellers (optional)','यात्रु संख्या (ऐच्छिक)'),'number']]:category==='education'?[[t('Institution (optional)','संस्था (ऐच्छिक)'),'text'],[t('Application or course (optional)','आवेदन वा पाठ्यक्रम (ऐच्छिक)'),'text'],[t('Deadline, if known (optional)','थाहा भए अन्तिम मिति (ऐच्छिक)'),'date']]:category==='utilities'?[[t('Provider name (optional)','प्रदायकको नाम (ऐच्छिक)'),'text']]:category==='government'?[[t('Application or correction needed (optional)','आवेदन वा सुधारको विवरण (ऐच्छिक)'),'text']]:category==='banking'?[[t('Bank or wallet provider (optional)','बैंक वा वालेट प्रदायक (ऐच्छिक)'),'text']]:[];for(const [title,type] of fields){const label=element('label',title),input=document.createElement('input');input.type=type;input.maxLength=100;if(type==='number'){input.min='1';input.max='100';input.step='1';input.inputMode='numeric';}if(type==='date'){input.min='2020-01-01';input.max='2099-12-31';}input.dataset.question=title;label.append(input);questions.append(label);}}
 function taskOptions(){rememberTask();previousService=form.elements.service.value;task.replaceChildren();const option=element('option',t('Not sure / describe below','निश्चित छैन / तल लेख्नुहोस्'));option.value='';task.append(option);let tasks=[];try{tasks=JSON.parse(form.elements.service.selectedOptions[0]?.dataset.tasks||'[]');}catch{}for(const title of tasks){const o=element('option',title);o.value=title;task.append(o);}taskQuestions();extra.hidden=!questions.children.length;extra.open=false;const draft=taskDrafts.get(previousService);if(draft){if([...task.options].some(o=>o.value===draft.task))task.value=draft.task;[...questions.querySelectorAll('input')].forEach((input,i)=>input.value=draft.answers[i]||'');}}
 form.elements.service.addEventListener('change',taskOptions);taskOptions();const requestedTask=new URLSearchParams(location.search).get('task');if(requestedTask&&[...task.options].some(o=>o.value===requestedTask))task.value=requestedTask;
 const message=form.elements.message,note=element('span',t('Optional when you have selected a task or answered a service question. Otherwise, briefly describe what you need.','काम छानेको वा सेवाको प्रश्नको उत्तर दिएको भए ऐच्छिक। नभए आफ्नो आवश्यकता छोटकरीमा लेख्नुहोस्।'),'small');message.closest('label').append(note);
 function messageRequirement(){message.required=!task.value&&![...questions.querySelectorAll('input')].some(input=>input.value.trim().length>=3);message.setCustomValidity('');}
 form.addEventListener('input',messageRequirement);form.addEventListener('change',messageRequirement);messageRequirement();
 const review=document.createElement('div');review.className='request-review';sections[2].insertBefore(review,sections[2].children[1]);
 const progress=element('p','','wizard-progress');progress.setAttribute('role','status');progress.tabIndex=-1;form.insertBefore(progress,sections[0]);
 const controls=document.createElement('div');controls.className='actions wizard-controls';const back=element('button',t('Back','पछाडि'),'button secondary'),next=element('button',t('Continue','अगाडि'),'button');back.type=next.type='button';controls.append(back,next);form.insertBefore(controls,submit);
 const meter=element('div','','step-meter');meter.setAttribute('aria-hidden','true');for(let i=0;i<3;i++)meter.append(element('span',''));progress.after(meter);
 let step=0,editingReview=false;
 function show(){sections.forEach((section,i)=>section.hidden=i!==step);back.hidden=step===0;next.hidden=step===2;submit.hidden=step!==2;next.textContent=editingReview?t('Return to review','पुनः जाँचमा फर्कनुहोस्'):t('Continue','अगाडि');[...meter.children].forEach((segment,i)=>segment.classList.toggle('is-complete',i<=step));progress.textContent=t(`Step ${step+1} of 3: ${titles[step]}`,`चरण ${step+1}/३: ${titles[step]}`);if(step===2){review.replaceChildren();for(const [index,fields] of [[0,[['service',t('Service','सेवा')],['message',t('Your request','अनुरोध')]]],[1,[['name',t('Name','नाम')],['phone',t('Phone','फोन')],['callback_window',t('Callback preference','फोनको प्राथमिकता')]]]]){const group=element('section','','review-group'),header=element('div','','review-heading'),button=element('button',t('Edit','सच्याउनुहोस्'),'button secondary');button.type='button';button.setAttribute('aria-label',t('Edit '+titles[index],titles[index]+' सच्याउनुहोस्'));button.addEventListener('click',()=>{if(form.dataset.busy==='true'||form.dataset.complete==='true')return;editingReview=true;step=index;form.elements.consent.checked=false;show();sections[index].querySelector('input,select,textarea')?.focus();});header.append(element('h3',titles[index]),button);const list=element('dl','');for(const [name,title] of fields){const input=form.elements[name];list.append(element('dt',title),element('dd',(name==='service'||name==='callback_window')?input.selectedOptions[0]?.textContent:name==='message'?requestMessage(form):input.value));}group.append(header,list);review.append(group);}}}
 function advance(){form.elements.message.setCustomValidity(requestMessage(form).length>1500?t('Please shorten your details to 1,500 characters in total.','कृपया जम्मा विवरण १५०० अक्षरभित्र छोट्याउनुहोस्।'):'');if(form.dataset.busy==='true'||form.dataset.complete==='true')return;for(const input of sections[step].querySelectorAll('input,select,textarea')){if(!input.checkValidity()){if(questions.contains(input))extra.open=true;input.reportValidity();return;}}step=editingReview?2:Math.min(2,step+1);editingReview=false;show();progress.focus();}
 next.addEventListener('click',advance);back.addEventListener('click',()=>{if(form.dataset.busy==='true'||form.dataset.complete==='true')return;step=editingReview?2:Math.max(0,step-1);editingReview=false;show();progress.focus();});
 // The existing submission handler remains the only code that sends requests.
 form.addEventListener('submit',event=>{if(step!==2){event.preventDefault();event.stopImmediatePropagation();advance();}},true);
 form.addEventListener('invalid',event=>{const index=sections.findIndex(section=>section.contains(event.target));if(index>=0&&index!==step){step=index;show();}},true);
 form.addEventListener('request-finished',()=>{if(form.dataset.complete==='true'){sections.forEach(s=>s.hidden=true);controls.hidden=true;submit.hidden=true;meter.hidden=true;progress.textContent=t('Request sent — keep your request number below.','अनुरोध पठाइयो — तलको अनुरोध नम्बर राख्नुहोस्।');feedback.focus();}else{const invalid=form.querySelector('[aria-invalid=true]');if(invalid){const index=sections.findIndex(section=>section.contains(invalid));if(index>=0){step=index;show();}}}});
 show();
})();
