document.documentElement.classList.add('js');
const nepali=document.documentElement.lang==='ne';
const say=(en,ne)=>nepali?ne:en;
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#primary-nav');
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&toggle?.getAttribute('aria-expanded')==='true'){toggle.setAttribute('aria-expanded','false');nav.classList.remove('is-open');toggle.focus();}});
const theme=document.querySelector('.theme-toggle');
try{const saved=localStorage.getItem('nath-theme');if(saved==='dark'){document.documentElement.dataset.theme='dark';theme?.setAttribute('aria-pressed','true');}}catch{}
theme?.addEventListener('click',()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';theme.setAttribute('aria-pressed',String(dark));try{localStorage.setItem('nath-theme',dark?'dark':'light');}catch{}});
document.querySelector('#service-search')?.addEventListener('input',e=>{let count=0;const value=e.target.value.trim().toLocaleLowerCase();document.querySelectorAll('[data-service]').forEach(card=>{card.hidden=!card.dataset.service.toLocaleLowerCase().includes(value);if(!card.hidden)count++;});document.querySelector('#search-status').textContent=say(`${count} services found`,`${count} सेवा भेटियो`);});
const requestForm=document.querySelector('#request-form');
if(requestForm){const selected=new URLSearchParams(location.search).get('service');if([...requestForm.elements.service.options].some(o=>o.value===selected))requestForm.elements.service.value=selected;let key;try{key=sessionStorage.getItem('nath-request-key');}catch{}if(!key){key=crypto.randomUUID();try{sessionStorage.setItem('nath-request-key',key);}catch{}}
 let busy=false,completed=false;const feedback=document.querySelector('#form-feedback');
 requestForm.addEventListener('submit',async e=>{e.preventDefault();if(busy||completed)return;requestForm.querySelectorAll('[aria-invalid]').forEach(x=>x.removeAttribute('aria-invalid'));if(!requestForm.reportValidity())return;
  busy=true;const button=requestForm.querySelector('button[type=submit]');button.disabled=true;feedback.textContent=say('Sending your request…','अनुरोध पठाइँदैछ…');feedback.dataset.error='false';
  const data=new FormData(requestForm);const payload={name:data.get('name'),phone:data.get('phone'),service:data.get('service'),message:data.get('message'),website:data.get('website'),consent:data.get('consent')==='on'};
  try{const response=await fetch('/api/requests',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});const result=await response.json();
   if(!response.ok){for(const field of Object.keys(result.fields||{}))requestForm.elements[field]?.setAttribute('aria-invalid','true');throw new Error(response.status===422?say('Please check your name, Nepal mobile number, service, message and consent.','नाम, नेपाली मोबाइल नम्बर, सेवा, सन्देश र सहमति जाँच गर्नुहोस्।'):response.status===409?say('An earlier attempt used different details. Contact us before sending another request.','पहिलेको प्रयासमा फरक विवरण थियो। अर्को अनुरोधअघि सम्पर्क गर्नुहोस्।'):response.status===429?say('Please wait one minute before trying again.','पुनः प्रयासअघि एक मिनेट पर्खनुहोस्।'):say('Online requests are temporarily unavailable. Please call or use WhatsApp.','अनलाइन अनुरोध अस्थायी रूपमा उपलब्ध छैन। फोन वा WhatsApp गर्नुहोस्।'));}
   completed=true;requestForm.reset();feedback.replaceChildren();const heading=document.createElement('strong');heading.textContent=say('Your request has been saved.','तपाईंको अनुरोध सुरक्षित भयो।');const reference=document.createElement('p');reference.textContent=say('Keep this reference: ','यो सन्दर्भ राख्नुहोस्: ')+result.reference;const note=document.createElement('p');note.textContent=say('Our team will review it during working hours. This is not a booking or payment confirmation.','टोलीले कार्यालय समयमा समीक्षा गर्नेछ। यो बुकिङ वा भुक्तानी पुष्टि होइन।');feedback.append(heading,reference,note);const actions=document.createElement('div');actions.className='reference-actions';const copy=document.createElement('button');copy.type='button';copy.className='button secondary';copy.textContent=say('Copy request number','अनुरोध नम्बर कपी गर्नुहोस्');copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(result.reference);copy.textContent=say('Copied','कपी भयो');}catch{copy.textContent=say('Select and copy the number above','माथिको नम्बर छानेर कपी गर्नुहोस्');}});const track=document.createElement('a');track.className='button';track.href=(nepali?'/ne':'')+'/track#'+encodeURIComponent(result.reference);track.textContent=say('Track this request','यो अनुरोध हेर्नुहोस्');actions.append(copy,track);feedback.append(actions);try{sessionStorage.removeItem('nath-request-key');}catch{}
  }catch(error){feedback.dataset.error='true';feedback.textContent=error.name==='TimeoutError'||error instanceof TypeError?say('We could not confirm the result. Retry with the same details; this will not create a duplicate. You can also call us.','नतिजा पुष्टि भएन। उही विवरणसहित पुनः प्रयास गर्दा दोहोरो अनुरोध बन्दैन। फोन पनि गर्न सक्नुहुन्छ।'):error.message;}
  finally{busy=false;button.disabled=completed;feedback.focus();}
 });
}
document.querySelector('#track-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button'),out=document.querySelector('#track-feedback');if(button.disabled)return;button.disabled=true;out.textContent=say('Checking…','जाँच हुँदैछ…');try{const data=new FormData(form);const r=await fetch('/api/track',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference:data.get('reference'),phone:data.get('phone')}),signal:AbortSignal.timeout(15000)});const v=await r.json();if(!r.ok)throw Error();const names={new:['Received — awaiting review','प्राप्त — समीक्षाको प्रतीक्षामा'],contacted:['Our team has contacted you','टोलीले सम्पर्क गरेको छ'],in_progress:['In progress','प्रक्रियामा'],closed:['Closed — contact us with any questions','बन्द — प्रश्न भए सम्पर्क गर्नुहोस्']};out.textContent=v.status?(names[v.status]||names.new)[nepali?1:0]:say('No matching request found. Check both details or contact us.','मिल्दो अनुरोध भेटिएन। दुवै विवरण जाँच गर्नुहोस् वा सम्पर्क गर्नुहोस्।');if(v.status){renderNextStep(out,v);if(v.quote)renderQuote(out,v,form);}if(v.status&&v.outcome){const p=document.createElement('p');p.textContent=({completed:say('Completed','सम्पन्न'),cancelled:say('Cancelled','रद्द'),declined:say('Unable to fulfil','पूरा गर्न नसकिएको')})[v.outcome]||'';out.append(p);}if(v.status&&v.history?.length){const list=document.createElement('ol');list.className='status-timeline';for(const item of v.history){const li=document.createElement('li');li.textContent=(names[item.status]||names.new)[nepali?1:0]+' · '+new Intl.DateTimeFormat(nepali?'ne-NP':'en-GB',{timeZone:'Asia/Kathmandu',dateStyle:'medium',timeStyle:'short'}).format(new Date(item.created_at.replace(' ','T')+'Z'));list.append(li);}out.append(list);}}catch{out.textContent=say('Status is temporarily unavailable. Please call us for an update.','अवस्था अस्थायी रूपमा उपलब्ध छैन। जानकारीका लागि फोन गर्नुहोस्।');}finally{button.disabled=false;out.focus();}});

const trackReference=document.querySelector('#track-form [name=reference]');if(trackReference&&/^#NOS-[A-F0-9]{24}$/i.test(location.hash)){trackReference.value=location.hash.slice(1);history.replaceState(null,'',location.pathname);}

const serviceSearch=document.querySelector('#service-search');if(serviceSearch){serviceSearch.value=new URLSearchParams(location.search).get('q')||'';serviceSearch.dispatchEvent(new Event('input'));}
const guidance=document.querySelector('#service-guidance'),serviceChoice=requestForm?.elements.service;
function updateGuidance(){if(!guidance||!serviceChoice)return;const option=serviceChoice.selectedOptions[0];const prompts={government:say('Which application or correction do you need? Mention the portal or office, if known.','कुन आवेदन वा विवरण सुधार चाहिएको हो? थाहा भए पोर्टल वा कार्यालयको नाम लेख्नुहोस्।'),utilities:say('Which bill and provider do you need help with? Do not share account passwords.','कुन बिल र प्रदायकका लागि सहयोग चाहिएको हो? खाताको पासवर्ड नलेख्नुहोस्।'),travel:say('Tell us your route, travel date and number of passengers. Booking depends on availability.','यात्राको स्थान, मिति र यात्रु संख्या बताउनुहोस्। बुकिङ उपलब्धतामा निर्भर हुन्छ।'),education:say('Name the institution, application and deadline, if known.','संस्था, आवेदन र थाहा भए अन्तिम मिति लेख्नुहोस्।'),banking:say('Describe the guidance you need. Do not share account numbers, PINs or OTPs.','कस्तो मार्गदर्शन चाहिएको हो बताउनुहोस्। खाता नम्बर, PIN वा OTP नलेख्नुहोस्।')};guidance.textContent=option?.dataset.guidance||prompts[serviceChoice.value]||say('Tell us the exact task and any relevant deadline. For travel include route and date; for bills include the provider; for forms include the application name. Do not enter document numbers, passwords, PINs or OTPs.','कामको नाम र समयसीमा बताउनुहोस्। यात्राका लागि स्थान र मिति, बिलका लागि प्रदायक, फारामका लागि आवेदनको नाम लेख्नुहोस्। कागजात नम्बर, पासवर्ड, PIN वा OTP नलेख्नुहोस्।');}
serviceChoice?.addEventListener('change',updateGuidance);updateGuidance();
function showHours(){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kathmandu',weekday:'short',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value]));const open=parts.weekday!=='Sat'&&Number(parts.hour)>=9&&Number(parts.hour)<18;document.querySelectorAll('.business-hours').forEach(el=>el.textContent=open?say('Open now · Requests reviewed during business hours','अहिले खुला · कार्यालय समयमा अनुरोध समीक्षा हुन्छ'):say('Currently closed · Sun–Fri, 9 AM–6 PM Nepal time. Urgent help: WhatsApp us.','अहिले बन्द · आइतबार–शुक्रबार बिहान ९–साँझ ६, नेपाल समय। अत्यावश्यक सहयोग: WhatsApp गर्नुहोस्।'));}showHours();setInterval(showHours,60000);
function renderNextStep(out,v){const next={new:say('Next: our team will review your request during working hours. Keep your request number.','अर्को चरण: टोलीले कार्यालय समयमा समीक्षा गर्नेछ। अनुरोध नम्बर राख्नुहोस्।'),contacted:say('Next: review the requirements discussed with our team. Contact us if you missed our message.','अर्को चरण: टोलीले बताएको आवश्यकता जाँच्नुहोस्। सन्देश छुटे सम्पर्क गर्नुहोस्।'),in_progress:say('Our team is working on your request. Contact us before changing any submitted details.','टोलीले अनुरोधमा काम गर्दैछ। विवरण परिवर्तनअघि सम्पर्क गर्नुहोस्।'),closed:say('This request is closed. Contact us with your request number if you need further help.','यो अनुरोध बन्द छ। थप सहयोगका लागि अनुरोध नम्बर सहित सम्पर्क गर्नुहोस्।')};const p=document.createElement('p');p.textContent=next[v.status];out.append(p);}
function renderQuote(out,v,form){const quoteReference=form.elements.reference.value,quotePhone=form.elements.phone.value;const box=document.createElement('section'),heading=document.createElement('h3');heading.textContent=say('Your quote','तपाईंको शुल्क विवरण');box.append(heading);let total=0;for(const item of v.quote.items){total+=item.paisa;const p=document.createElement('p');p.textContent=item.description+' — NPR '+(item.paisa/100).toFixed(2);box.append(p);}const sum=document.createElement('strong');sum.textContent=say('Total: NPR ','कुल: रु. ')+(total/100).toFixed(2);box.append(sum);const note=document.createElement('p');note.textContent=v.quote.accepted?say('You accepted this quote. Acceptance does not make a payment.','तपाईंले यो शुल्क स्वीकार गर्नुभयो। स्वीकार गर्दा भुक्तानी हुँदैन।'):say('Review every charge before accepting. Acceptance does not make a payment or guarantee approval by a provider.','स्वीकार गर्नुअघि सबै शुल्क जाँच्नुहोस्। स्वीकार गर्दा भुक्तानी हुँदैन वा प्रदायकको स्वीकृतिको ग्यारेन्टी हुँदैन।');box.append(note);
 if(v.quote.accepted){const p=document.createElement('p');p.className='preserve-lines';p.textContent=v.quote.payment_instructions||say('Contact our team for verified payment instructions before paying. Never share PINs or OTPs.','भुक्तानीअघि टोलीसँग आधिकारिक विवरण पुष्टि गर्नुहोस्। PIN वा OTP नदिनुहोस्।');box.append(p);}else if(v.status!=='closed'){const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';label.append(check,document.createTextNode(say(' I reviewed and agree to these charges.',' मैले शुल्क जाँचेर सहमति दिएको छु।')));const button=document.createElement('button');button.type='button';button.className='button';button.textContent=say('Accept this quote','यो शुल्क स्वीकार गर्नुहोस्');button.disabled=true;check.addEventListener('change',()=>button.disabled=!check.checked);button.addEventListener('click',async()=>{button.disabled=true;try{const r=await fetch('/api/quote-accept',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference:quoteReference,phone:quotePhone,revision:v.quote.revision,accept:true}),signal:AbortSignal.timeout(15000)});const result=await r.json();if(!r.ok||!result.accepted)throw Error();form.requestSubmit();}catch{note.textContent=say('Could not confirm acceptance. Check your request again; the quote may have changed.','स्वीकृति पुष्टि भएन। शुल्क परिवर्तन भएको हुन सक्छ; फेरि जाँच्नुहोस्।');button.disabled=false;}});box.append(label,button);}out.append(box);}
