document.documentElement.classList.add('js');
const nepali=document.documentElement.lang==='ne';
const say=(en,ne)=>nepali?ne:en;
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#primary-nav');
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&toggle?.getAttribute('aria-expanded')==='true'){toggle.setAttribute('aria-expanded','false');nav.classList.remove('is-open');toggle.focus();}});
const theme=document.querySelector('.theme-toggle');
try{const saved=localStorage.getItem('nath-theme');if(saved==='dark'){document.documentElement.dataset.theme='dark';theme?.setAttribute('aria-pressed','true');}}catch{}
theme?.addEventListener('click',()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';theme.setAttribute('aria-pressed',String(dark));try{localStorage.setItem('nath-theme',dark?'dark':'light');}catch{}});
function serviceSearchText(value){return value.normalize('NFKC').toLocaleLowerCase().replace(/[-–—]/g,' ').replace(/\s+/g,' ').trim();}
const serviceAliases=[['passport','pasport','राहदानी'],['electricity','electric','bijuli','बिजुली','विद्युत्'],['water','pani','पानी','खानेपानी'],['ticket','tickets','tikat','टिकट'],['scholarship','छात्रवृत्ति'],['citizenship','nagarikta','नागरिकता'],['pan','प्यान'],['internet','wifi','इन्टरनेट'],['bus','बस'],['airline','flight','हवाई']];
function matchesService(text,query){const haystack=serviceSearchText(text);return serviceSearchText(query).split(' ').filter(Boolean).every(word=>{const aliases=serviceAliases.find(group=>group.includes(word))||[word];return aliases.some(alias=>haystack.includes(alias));});}
function filterServices(){const search=document.querySelector('#service-search');if(!search)return;let count=0;const query=search.value.trim().toLocaleLowerCase(),category=document.querySelector('#category-filter')?.value||'',available=document.querySelector('#availability-filter')?.value||'';const cards=[...document.querySelectorAll('[data-service]')];for(const card of cards){card.hidden=!matchesService(card.dataset.service,query)||(category&&card.dataset.category!==category)||(available&&card.dataset.available!==available);if(!card.hidden)count++;}const sort=document.querySelector('#service-sort')?.value;cards.sort((a,b)=>sort==='price'?Number(a.dataset.price)-Number(b.dataset.price):sort==='name'?a.querySelector('h3').textContent.localeCompare(b.querySelector('h3').textContent,nepali?'ne':'en'):Number(a.dataset.order)-Number(b.dataset.order));for(const card of cards)card.parentElement.append(card);document.querySelector('#search-status').textContent=say(`${count} ${count===1?'service':'services'} found`,`${count} सेवा भेटियो`);const empty=document.querySelector('#no-services');if(empty){empty.hidden=count!==0;let link=empty.querySelector('a');if(link){link.textContent=say('Describe what you need','आफ्नो आवश्यकता बताउनुहोस्');link.href=(nepali?'/ne':'')+'/request#help='+encodeURIComponent(search.value.trim().slice(0,300));}}}
document.querySelector('#service-search')?.addEventListener('input',filterServices);
for(const id of ['category-filter','availability-filter','service-sort'])document.getElementById(id)?.addEventListener('change',filterServices);
document.querySelector('#clear-filters')?.addEventListener('click',()=>{document.querySelector('#service-search').value='';for(const id of ['category-filter','availability-filter','service-sort'])document.getElementById(id).selectedIndex=0;filterServices();document.querySelector('#service-search').focus();});
const requestForm=document.querySelector('#request-form');
if(requestForm){const selected=new URLSearchParams(location.search).get('service');if([...requestForm.elements.service.options].some(o=>o.value===selected))requestForm.elements.service.value=selected;let key;try{key=sessionStorage.getItem('nath-request-key');}catch{}if(!key){key=crypto.randomUUID();try{sessionStorage.setItem('nath-request-key',key);}catch{}}
 let busy=false,completed=false;const feedback=document.querySelector('#form-feedback');
 requestForm.addEventListener('submit',async e=>{e.preventDefault();if(busy||completed)return;requestForm.querySelectorAll('[aria-invalid]').forEach(x=>x.removeAttribute('aria-invalid'));if(!requestForm.reportValidity())return;
  busy=true;requestForm.dataset.busy='true';const button=requestForm.querySelector('button[type=submit]');button.disabled=true;feedback.textContent=say('Sending your request…','अनुरोध पठाइँदैछ…');feedback.dataset.error='false';
  const data=new FormData(requestForm);const payload={name:data.get('name'),phone:data.get('phone'),service:data.get('service'),message:requestMessage(requestForm),callback_window:data.get('callback_window')||'',website:data.get('website'),consent:data.get('consent')==='on'};
  try{const response=await fetch('/api/requests',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});const result=await response.json();
   if(!response.ok){for(const field of Object.keys(result.fields||{}))requestForm.elements[field]?.setAttribute('aria-invalid','true');throw new Error(response.status===422?say('Please check your name, Nepal mobile number, service, message and consent.','नाम, नेपाली मोबाइल नम्बर, सेवा, सन्देश र सहमति जाँच गर्नुहोस्।'):response.status===409?say('An earlier attempt used different details. Contact us before sending another request.','पहिलेको प्रयासमा फरक विवरण थियो। अर्को अनुरोधअघि सम्पर्क गर्नुहोस्।'):response.status===429?say('Please wait one minute before trying again.','पुनः प्रयासअघि एक मिनेट पर्खनुहोस्।'):say('Online requests are temporarily unavailable. Please call or use WhatsApp.','अनलाइन अनुरोध अस्थायी रूपमा उपलब्ध छैन। फोन वा WhatsApp गर्नुहोस्।'));}
   completed=true;requestForm.reset();feedback.replaceChildren();const heading=document.createElement('strong');heading.textContent=say('Your request has been saved.','तपाईंको अनुरोध सुरक्षित भयो।');const reference=document.createElement('p');reference.textContent=say('Keep this reference: ','यो सन्दर्भ राख्नुहोस्: ')+result.reference;const note=document.createElement('p');note.textContent=say('Our team will review it during working hours. This is not a booking or payment confirmation.','टोलीले कार्यालय समयमा समीक्षा गर्नेछ। यो बुकिङ वा भुक्तानी पुष्टि होइन।');feedback.append(heading,reference,note);const actions=document.createElement('div');actions.className='reference-actions';const copy=document.createElement('button');copy.type='button';copy.className='button secondary';copy.textContent=say('Copy request number','अनुरोध नम्बर कपी गर्नुहोस्');copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(result.reference);copy.textContent=say('Copied','कपी भयो');}catch{copy.textContent=say('Select and copy the number above','माथिको नम्बर छानेर कपी गर्नुहोस्');}});const track=document.createElement('a');track.className='button';track.href=(nepali?'/ne':'')+'/track#'+encodeURIComponent(result.reference);track.textContent=say('Track this request','यो अनुरोध हेर्नुहोस्');const print=document.createElement('button');print.type='button';print.className='button secondary';print.textContent=say('Print confirmation','पुष्टि प्रिन्ट गर्नुहोस्');print.addEventListener('click',()=>window.print());feedback.classList.add('request-confirmation');const next=document.createElement('p');next.textContent=say('Next: keep this number and use the same phone number to track replies and review your quote. Sun–Fri, 9 AM–6 PM Nepal time.','अर्को चरण: यो नम्बर राख्नुहोस्। जवाफ र शुल्क हेर्न यही फोन नम्बर प्रयोग गर्नुहोस्। आइत–शुक्र, बिहान ९–साँझ ६, नेपाल समय।');feedback.append(next);actions.append(copy,track,print,requestWhatsApp(result.reference));feedback.append(actions);try{sessionStorage.removeItem('nath-request-key');}catch{}
  }catch(error){feedback.dataset.error='true';feedback.textContent=error.name==='TimeoutError'||error instanceof TypeError?say('We could not confirm the result. Retry with the same details; this will not create a duplicate. You can also call us.','नतिजा पुष्टि भएन। उही विवरणसहित पुनः प्रयास गर्दा दोहोरो अनुरोध बन्दैन। फोन पनि गर्न सक्नुहुन्छ।'):error.message;}
  finally{busy=false;requestForm.dataset.busy='false';requestForm.dataset.complete=String(completed);requestForm.dispatchEvent(new Event('request-finished'));button.disabled=completed;feedback.focus();}
 });
}
document.querySelector('#track-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button'),out=document.querySelector('#track-feedback');if(button.disabled)return;button.disabled=true;out.textContent=say('Checking…','जाँच हुँदैछ…');try{const data=new FormData(form);const r=await fetch('/api/track',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference:data.get('reference'),phone:data.get('phone')}),signal:AbortSignal.timeout(15000)});const v=await r.json();if(!r.ok)throw Error();const names={new:['Received — awaiting review','प्राप्त — समीक्षाको प्रतीक्षामा'],contacted:['Our team has contacted you','टोलीले सम्पर्क गरेको छ'],in_progress:['In progress','प्रक्रियामा'],closed:['Closed — contact us with any questions','बन्द — प्रश्न भए सम्पर्क गर्नुहोस्']};out.textContent=v.status?(names[v.status]||names.new)[nepali?1:0]:say('No matching request found. Check both details or contact us.','मिल्दो अनुरोध भेटिएन। दुवै विवरण जाँच गर्नुहोस् वा सम्पर्क गर्नुहोस्।');if(v.status){renderTrackingSummary(out,v,form);out.append(requestWhatsApp(form.elements.reference.value.trim().toUpperCase()));renderNextStep(out,v);if(v.conversation)renderConversation(out,v,form);if(v.quote)renderQuote(out,v,form);}if(v.status&&v.outcome){const p=document.createElement('p');p.textContent=({completed:say('Completed','सम्पन्न'),cancelled:say('Cancelled','रद्द'),declined:say('Unable to fulfil','पूरा गर्न नसकिएको')})[v.outcome]||'';out.append(p);}if(v.status&&v.history?.length){const list=document.createElement('ol');list.className='status-timeline';for(const item of v.history){const li=document.createElement('li');li.textContent=(names[item.status]||names.new)[nepali?1:0]+' · '+new Intl.DateTimeFormat(nepali?'ne-NP':'en-GB',{timeZone:'Asia/Kathmandu',dateStyle:'medium',timeStyle:'short'}).format(new Date(item.created_at.replace(' ','T')+'Z'));list.append(li);}const panel=document.createElement('section'),heading=document.createElement('h3');heading.textContent=say('Request progress','अनुरोधको प्रगति');panel.append(heading,list);out.append(panel);}}catch{out.textContent=say('Status is temporarily unavailable. Please call us for an update.','अवस्था अस्थायी रूपमा उपलब्ध छैन। जानकारीका लागि फोन गर्नुहोस्।');}finally{button.disabled=false;out.focus();}});

const trackReference=document.querySelector('#track-form [name=reference]');if(trackReference&&/^#NOS-[A-F0-9]{24}$/i.test(location.hash)){trackReference.value=location.hash.slice(1);history.replaceState(null,'',location.pathname);}

const serviceSearch=document.querySelector('#service-search');if(serviceSearch){serviceSearch.value=new URLSearchParams(location.search).get('q')||'';const category=new URLSearchParams(location.search).get('category');const field=document.querySelector('#category-filter');if(field&&[...field.options].some(o=>o.value===category))field.value=category;serviceSearch.dispatchEvent(new Event('input'));}
const guidance=document.querySelector('#service-guidance'),serviceChoice=requestForm?.elements.service;
function updateGuidance(){if(!guidance||!serviceChoice)return;const option=serviceChoice.selectedOptions[0];const prompts={government:say('Which application or correction do you need? Mention the portal or office, if known.','कुन आवेदन वा विवरण सुधार चाहिएको हो? थाहा भए पोर्टल वा कार्यालयको नाम लेख्नुहोस्।'),utilities:say('Which bill and provider do you need help with? Do not share account passwords.','कुन बिल र प्रदायकका लागि सहयोग चाहिएको हो? खाताको पासवर्ड नलेख्नुहोस्।'),travel:say('Tell us your route, travel date and number of passengers. Booking depends on availability.','यात्राको स्थान, मिति र यात्रु संख्या बताउनुहोस्। बुकिङ उपलब्धतामा निर्भर हुन्छ।'),education:say('Name the institution, application and deadline, if known.','संस्था, आवेदन र थाहा भए अन्तिम मिति लेख्नुहोस्।'),banking:say('Describe the guidance you need. Do not share account numbers, PINs or OTPs.','कस्तो मार्गदर्शन चाहिएको हो बताउनुहोस्। खाता नम्बर, PIN वा OTP नलेख्नुहोस्।')};guidance.textContent=option?.dataset.guidance||prompts[serviceChoice.value]||say('Tell us the exact task and any relevant deadline. For travel include route and date; for bills include the provider; for forms include the application name. Do not enter document numbers, passwords, PINs or OTPs.','कामको नाम र समयसीमा बताउनुहोस्। यात्राका लागि स्थान र मिति, बिलका लागि प्रदायक, फारामका लागि आवेदनको नाम लेख्नुहोस्। कागजात नम्बर, पासवर्ड, PIN वा OTP नलेख्नुहोस्।');}
serviceChoice?.addEventListener('change',updateGuidance);updateGuidance();
function showHours(){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kathmandu',weekday:'short',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value]));const open=parts.weekday!=='Sat'&&Number(parts.hour)>=9&&Number(parts.hour)<18;document.querySelectorAll('.business-hours').forEach(el=>el.textContent=open?say('Open now · Requests reviewed during business hours','अहिले खुला · कार्यालय समयमा अनुरोध समीक्षा हुन्छ'):say('Currently closed · Sun–Fri, 9 AM–6 PM Nepal time. Urgent help: WhatsApp us.','अहिले बन्द · आइतबार–शुक्रबार बिहान ९–साँझ ६, नेपाल समय। अत्यावश्यक सहयोग: WhatsApp गर्नुहोस्।'));}showHours();setInterval(showHours,60000);
function renderNextStep(out,v){const panel=document.createElement('section');panel.className='next-action-card';out.append(panel);out=panel;const title=document.createElement('h3');title.textContent=say('Your next action','तपाईंको अर्को कदम');out.append(title);const next={new:say('Next: our team will review your request during working hours. Keep your request number.','अर्को चरण: टोलीले कार्यालय समयमा समीक्षा गर्नेछ। अनुरोध नम्बर राख्नुहोस्।'),contacted:say('Next: review the requirements discussed with our team. Contact us if you missed our message.','अर्को चरण: टोलीले बताएको आवश्यकता जाँच्नुहोस्। सन्देश छुटे सम्पर्क गर्नुहोस्।'),in_progress:say('Our team is working on your request. Contact us before changing any submitted details.','टोलीले अनुरोधमा काम गर्दैछ। विवरण परिवर्तनअघि सम्पर्क गर्नुहोस्।'),closed:say('This request is closed. Contact us with your request number if you need further help.','यो अनुरोध बन्द छ। थप सहयोगका लागि अनुरोध नम्बर सहित सम्पर्क गर्नुहोस्।')};const p=document.createElement('p');p.textContent=v.conversation?.waiting&&v.status!=='closed'?say('Waiting for you: read our team’s message below and reply with the requested details.','तपाईंको जवाफको प्रतीक्षामा: तल टोलीको सन्देश पढेर मागिएको विवरण पठाउनुहोस्।'):v.quote&&!v.quote.accepted&&v.status!=='closed'?say('Review the quote below and accept it only if you agree with the charges.','तलको शुल्क जाँच्नुहोस् र सहमत भए मात्र स्वीकार गर्नुहोस्।'):v.quote?.accepted&&v.status!=='closed'?say('Your quote is accepted. Follow the verified instructions below or contact the team before paying.','शुल्क स्वीकार भयो। तलका पुष्टि गरिएका निर्देशन पालना गर्नुहोस् वा भुक्तानीअघि टोलीसँग सम्पर्क गर्नुहोस्।'):next[v.status];out.append(p);}
function renderQuote(out,v,form){const quoteReference=form.elements.reference.value,quotePhone=form.elements.phone.value;const box=document.createElement('section'),heading=document.createElement('h3');heading.textContent=say('Your quote','तपाईंको शुल्क विवरण');box.append(heading);let total=0;for(const item of v.quote.items){total+=item.paisa;const p=document.createElement('p');p.textContent=item.description+' — NPR '+(item.paisa/100).toFixed(2);box.append(p);}const sum=document.createElement('strong');sum.textContent=say('Total: NPR ','कुल: रु. ')+(total/100).toFixed(2);box.append(sum);const note=document.createElement('p');note.textContent=v.quote.accepted?say('You accepted this quote. Acceptance does not make a payment.','तपाईंले यो शुल्क स्वीकार गर्नुभयो। स्वीकार गर्दा भुक्तानी हुँदैन।'):say('Review every charge before accepting. Acceptance does not make a payment or guarantee approval by a provider.','स्वीकार गर्नुअघि सबै शुल्क जाँच्नुहोस्। स्वीकार गर्दा भुक्तानी हुँदैन वा प्रदायकको स्वीकृतिको ग्यारेन्टी हुँदैन।');box.append(note);
 if(v.quote.accepted){const p=document.createElement('p');p.className='preserve-lines';p.textContent=v.quote.payment_instructions||say('Contact our team for verified payment instructions before paying. Never share PINs or OTPs.','भुक्तानीअघि टोलीसँग आधिकारिक विवरण पुष्टि गर्नुहोस्। PIN वा OTP नदिनुहोस्।');box.append(p);}else if(v.status!=='closed'){const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';label.append(check,document.createTextNode(say(' I reviewed and agree to these charges.',' मैले शुल्क जाँचेर सहमति दिएको छु।')));const button=document.createElement('button');button.type='button';button.className='button';button.textContent=say('Accept this quote','यो शुल्क स्वीकार गर्नुहोस्');button.disabled=true;check.addEventListener('change',()=>button.disabled=!check.checked);button.addEventListener('click',async()=>{button.disabled=true;try{const r=await fetch('/api/quote-accept',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference:quoteReference,phone:quotePhone,revision:v.quote.revision,accept:true}),signal:AbortSignal.timeout(15000)});const result=await r.json();if(!r.ok||!result.accepted)throw Error();form.requestSubmit();}catch{note.textContent=say('Could not confirm acceptance. Check your request again; the quote may have changed.','स्वीकृति पुष्टि भएन। शुल्क परिवर्तन भएको हुन सक्छ; फेरि जाँच्नुहोस्।');button.disabled=false;}});box.append(label,button);}out.append(box);}

function requestWhatsApp(reference){const link=document.createElement('a');link.className='button secondary';link.textContent=say('Ask on WhatsApp about this request','यो अनुरोधबारे WhatsApp मा सोध्नुहोस्');link.href='https://wa.me/9779867302353?text='+encodeURIComponent(say('Hello Nath, please help me with request ','नमस्ते नाथ, यो अनुरोधमा सहयोग गर्नुहोस्: ')+reference);link.target='_blank';link.rel='noopener noreferrer';return link;}

function requestMessage(form){const lines=[];const task=form.elements.task_choice?.value;if(task)lines.push(say('Task: ','काम: ')+task);for(const input of form.querySelectorAll('[data-question]'))if(input.value.trim())lines.push(input.dataset.question+': '+input.value.trim());lines.push(form.elements.message.value.trim());return lines.filter(Boolean).join('\n');}

function renderConversation(out,v,form){
 const reference=form.elements.reference.value.trim().toUpperCase(),phone=form.elements.phone.value,box=document.createElement('section'),heading=document.createElement('h3');heading.textContent=say('Messages with our team','टोलीसँगका सन्देश');box.append(heading);
 if(v.conversation.hasMore){const note=document.createElement('p');note.textContent=say('Showing the latest 50 messages. Contact the team for older details.','पछिल्ला ५० सन्देश देखाइएका छन्। पुराना विवरणका लागि टोलीसँग सम्पर्क गर्नुहोस्।');box.append(note);}
 for(const message of v.conversation.messages){const item=document.createElement('p');item.className='preserve-lines';item.textContent=(message.sender==='team'?say('Nath team','नाथ टोली'):say('You','तपाईं'))+' · '+new Intl.DateTimeFormat(nepali?'ne-NP':'en-GB',{timeZone:'Asia/Kathmandu',dateStyle:'medium',timeStyle:'short'}).format(new Date(message.created_at.replace(' ','T')+'Z'))+'\n'+message.body;box.append(item);}
 if(v.status!=='closed'){const label=document.createElement('label');label.textContent=say('Your reply (text only)','तपाईंको जवाफ (पाठ मात्र)');const input=document.createElement('textarea');input.maxLength=1500;input.rows=3;label.append(input);const hint=document.createElement('p');hint.textContent=say('Do not share passwords, PINs, OTPs or document numbers. Messages are reviewed during working hours.','पासवर्ड, PIN, OTP वा कागजात नम्बर नदिनुहोस्। कार्यालय समयमा सन्देश समीक्षा गरिन्छ।');const button=document.createElement('button');button.type='button';button.className='button';button.textContent=say('Send reply','जवाफ पठाउनुहोस्');const status=document.createElement('p');status.setAttribute('role','status');let key=crypto.randomUUID(),attempt=null;
 button.addEventListener('click',async()=>{if(!input.value.trim()){status.textContent=say('Write a short reply first.','पहिले छोटो जवाफ लेख्नुहोस्।');input.focus();return;}const message=input.value.trim();if(attempt!==null&&attempt!==message){status.textContent=say('The earlier result is uncertain. Check status again before changing your reply.','पहिलेको नतिजा निश्चित छैन। जवाफ फेर्नुअघि अवस्था फेरि जाँच्नुहोस्।');return;}attempt=message;button.disabled=true;input.readOnly=true;try{const response=await fetch('/api/reply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference,phone,message,key,version:v.conversation.version}),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok||!result.saved)throw Error();status.textContent=say('Reply saved. Check status again for new messages.','जवाफ सुरक्षित भयो। नयाँ सन्देशका लागि अवस्था फेरि जाँच्नुहोस्।');button.textContent=say('Reply sent','जवाफ पठाइयो');}catch{status.textContent=say('Could not confirm your reply. Retry unchanged, or check status again; the request may have changed.','जवाफ पुष्टि भएन। उही जवाफ पुनः प्रयास गर्नुहोस् वा अवस्था फेरि जाँच्नुहोस्; अनुरोध परिवर्तन भएको हुन सक्छ।');button.disabled=false;input.readOnly=false;}});box.append(label,hint,button,status);}out.append(box);
}

if(requestForm&&location.hash.startsWith('#help=')){try{requestForm.elements.message.value=decodeURIComponent(location.hash.slice(6)).slice(0,300);history.replaceState(null,'',location.pathname+location.search);}catch{}}

const serviceMenu=document.querySelector('.nav-services');
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&serviceMenu?.open){serviceMenu.open=false;if(nav.getClientRects().length)serviceMenu.querySelector('summary').focus();else toggle?.focus();}});
document.addEventListener('click',event=>{if(serviceMenu&&!serviceMenu.contains(event.target))serviceMenu.open=false;});
nav?.addEventListener('click',event=>{if(event.target.closest('a')){toggle.setAttribute('aria-expanded','false');nav.classList.remove('is-open');}});

function renderTrackingSummary(out,v,form){
 const panel=document.createElement('section');panel.className='tracking-summary';const title=document.createElement('h3');title.textContent=say('Request at a glance','अनुरोधको सारांश');panel.append(title);
 const list=document.createElement('dl');
 const updated=new Intl.DateTimeFormat(nepali?'ne-NP':'en-GB',{timeZone:'Asia/Kathmandu',dateStyle:'medium',timeStyle:'short'}).format(new Date(v.updated_at.replace(' ','T')+'Z'));
 const quote=v.quote?say('NPR ','रु. ')+(v.quote.items.reduce((sum,item)=>sum+item.paisa,0)/100).toFixed(2)+' · '+(v.quote.accepted?say('Accepted','स्वीकार गरिएको'):say('Awaiting your approval','तपाईंको स्वीकृतिको प्रतीक्षामा')):say('Not shared yet','अहिलेसम्म पठाइएको छैन');
 for(const [label,value] of [[say('Request number','अनुरोध नम्बर'),form.elements.reference.value.trim().toUpperCase()],[say('Status updated (Nepal time)','अवस्था अद्यावधिक (नेपाल समय)'),updated],[say('Quote','शुल्क विवरण'),quote]]){const term=document.createElement('dt'),detail=document.createElement('dd');term.textContent=label;detail.textContent=value;list.append(term,detail);}panel.append(list);out.append(panel);
}
