document.documentElement.classList.add('js');
const nepali=document.documentElement.lang==='ne';
const say=(en,ne)=>nepali?ne:en;
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#primary-nav');
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&toggle?.getAttribute('aria-expanded')==='true'){toggle.setAttribute('aria-expanded','false');nav.classList.remove('is-open');toggle.focus();}});
const theme=document.querySelector('.theme-toggle');
try{const saved=localStorage.getItem('nath-theme');if(saved==='dark'){document.documentElement.dataset.theme='dark';theme?.setAttribute('aria-pressed','true');}}catch{}
theme?.addEventListener('click',()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';theme.setAttribute('aria-pressed',String(dark));try{localStorage.setItem('nath-theme',dark?'dark':'light');}catch{}});
document.querySelector('#service-search')?.addEventListener('input',e=>{let count=0;const value=e.target.value.trim().toLocaleLowerCase();document.querySelectorAll('[data-service]').forEach(card=>{card.hidden=!card.dataset.service.toLocaleLowerCase().includes(value);if(!card.hidden)count++;});document.querySelector('#search-status').textContent=say(`${count} services found`,`${count} सेवा भेटियो`);});
const requestForm=document.querySelector('#request-form');
if(requestForm){const selected=new URLSearchParams(location.search).get('service');if([...requestForm.elements.service.options].some(o=>o.value===selected))requestForm.elements.service.value=selected;let key;try{key=sessionStorage.getItem('nath-request-key');}catch{}if(!key){key=crypto.randomUUID();try{sessionStorage.setItem('nath-request-key',key);}catch{}}
 let busy=false,completed=false;const feedback=document.querySelector('#form-feedback');
 requestForm.addEventListener('submit',async e=>{e.preventDefault();if(busy||completed)return;requestForm.querySelectorAll('[aria-invalid]').forEach(x=>x.removeAttribute('aria-invalid'));if(!requestForm.reportValidity())return;
  busy=true;const button=requestForm.querySelector('button[type=submit]');button.disabled=true;feedback.textContent=say('Sending your request…','अनुरोध पठाइँदैछ…');feedback.dataset.error='false';
  const data=new FormData(requestForm);const payload={name:data.get('name'),phone:data.get('phone'),service:data.get('service'),message:data.get('message'),website:data.get('website'),consent:data.get('consent')==='on'};
  try{const response=await fetch('/api/requests',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});const result=await response.json();
   if(!response.ok){for(const field of Object.keys(result.fields||{}))requestForm.elements[field]?.setAttribute('aria-invalid','true');throw new Error(response.status===422?say('Please check your name, Nepal mobile number, service, message and consent.','नाम, नेपाली मोबाइल नम्बर, सेवा, सन्देश र सहमति जाँच गर्नुहोस्।'):response.status===409?say('An earlier attempt used different details. Contact us before sending another request.','पहिलेको प्रयासमा फरक विवरण थियो। अर्को अनुरोधअघि सम्पर्क गर्नुहोस्।'):response.status===429?say('Please wait one minute before trying again.','पुनः प्रयासअघि एक मिनेट पर्खनुहोस्।'):say('Online requests are temporarily unavailable. Please call or use WhatsApp.','अनलाइन अनुरोध अस्थायी रूपमा उपलब्ध छैन। फोन वा WhatsApp गर्नुहोस्।'));}
   completed=true;requestForm.reset();feedback.replaceChildren();const heading=document.createElement('strong');heading.textContent=say('Your request has been saved.','तपाईंको अनुरोध सुरक्षित भयो।');const reference=document.createElement('p');reference.textContent=say('Keep this reference: ','यो सन्दर्भ राख्नुहोस्: ')+result.reference;const note=document.createElement('p');note.textContent=say('Our team will review it during working hours. This is not a booking or payment confirmation.','टोलीले कार्यालय समयमा समीक्षा गर्नेछ। यो बुकिङ वा भुक्तानी पुष्टि होइन।');feedback.append(heading,reference,note);try{sessionStorage.removeItem('nath-request-key');}catch{}
  }catch(error){feedback.dataset.error='true';feedback.textContent=error.name==='TimeoutError'||error instanceof TypeError?say('We could not confirm the result. Retry with the same details; this will not create a duplicate. You can also call us.','नतिजा पुष्टि भएन। उही विवरणसहित पुनः प्रयास गर्दा दोहोरो अनुरोध बन्दैन। फोन पनि गर्न सक्नुहुन्छ।'):error.message;}
  finally{busy=false;button.disabled=completed;feedback.focus();}
 });
}
document.querySelector('#track-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button'),out=document.querySelector('#track-feedback');if(button.disabled)return;button.disabled=true;out.textContent=say('Checking…','जाँच हुँदैछ…');try{const data=new FormData(form);const r=await fetch('/api/track',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference:data.get('reference'),phone:data.get('phone')}),signal:AbortSignal.timeout(15000)});const v=await r.json();if(!r.ok)throw Error();const names={new:['Received — awaiting review','प्राप्त — समीक्षाको प्रतीक्षामा'],contacted:['Our team has contacted you','टोलीले सम्पर्क गरेको छ'],in_progress:['In progress','प्रक्रियामा'],closed:['Closed — contact us with any questions','बन्द — प्रश्न भए सम्पर्क गर्नुहोस्']};out.textContent=v.status?(names[v.status]||names.new)[nepali?1:0]:say('No matching request found. Check both details or contact us.','मिल्दो अनुरोध भेटिएन। दुवै विवरण जाँच गर्नुहोस् वा सम्पर्क गर्नुहोस्।');}catch{out.textContent=say('Status is temporarily unavailable. Please call us for an update.','अवस्था अस्थायी रूपमा उपलब्ध छैन। जानकारीका लागि फोन गर्नुहोस्।');}finally{button.disabled=false;out.focus();}});
